### ISSUE TITLE
falco-exporter: Documentation about the falco gRPC socket communication

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/charts#102]
Hi there,

Unfortunately for me it's unclear how the falco-exporter should be able to access the falco output events. The [falco-exporter/README.md](https://github.com/falcosecurity/charts/tree/master/falco-exporter) lists the `falco.grpcUnixSocketPath` configuration possibility but does not say what needs to be configured on the other side in the falco Helm chart [falco/README.md](https://github.com/falcosecurity/charts/tree/master/falco#configuration) under the `falco.grpc.*` values. `falco.grpc.enabled` is by default set to `false` so my guess is that falco-exporter isn't even able to communicate with the falco socket by default...

Thanks!

Regards,
Philip

**Comment by leogr** [comment]
Hi,

falco-export connects to Falco via gRPC (over a Unix socket in the default configuration), enabling the gRPC is indeed a prerequisite.

The first section of the [falco-exporter chart README.md](https://github.com/falcosecurity/charts/blob/master/falco-exporter/README.md#falco-exporter-helm-chart) reports:

> # falco-exporter Helm Chart
> 
> [falco-exporter](https://github.com/falcosecurity/falco-exporter) is a Prometheus Metrics Exporter for Falco output events.
> 
> Before using this chart, you need [Falco installed](https://falco.org/docs/installation/) and running with the [gRPC Output](https://falco.org/docs/grpc/) enabled (over Unix socket by default).
> 
> This chart is compatible with the [Falco Chart](https://github.com/falcosecurity/charts/tree/master/falco) version `v1.2.0` or greater. Instructions to enable the gRPC Output in the Falco Helm Chart can be found [here](https://github.com/falcosecurity/charts/tree/master/falco#enabling-grpc). We also strongly recommend using [gRPC over Unix socket](https://github.com/falcosecurity/charts/tree/master/falco#grpc-over-unix-socket-default).

Anyway, I can understand that those instructions are maybe not so visible.  

Please, feel free to suggest any improvement that can make that more clear. I will be happy to help.

**Comment by PhilipSchmid** [comment]
Hi @leogr 

Sorry, my bad. I would have expected this hint in the description column of the `falco.grpcUnixSocketPath` configuration value.

Thanks!

Regards,
Philip
