### ISSUE TITLE
Enabling k8s audit event support not working on k8s version 1.18.5

### ISSUE THREAD

**Issue by SamarSidharth** [falcosecurity/charts#130]
**Describe the bug**
Unable to see the k8s audit events in the Falco logs after enabling the k8s audit event support

I have a local k8s setup with one master and one worker node, I am trying to enable the k8s audit event support by following https://github.com/falcosecurity/charts/tree/falco-1.5.1/falco link. I am able to execute the instructions successfully but not able to see the k8s audit events in the Falco logs.

Apiserver flags:
Option1:
    - --audit-log-path=/var/lib/k8s_audit/k8s_audit_events.log
    - --audit-policy-file=/var/lib/k8s_audit/audit-policy.yaml
    - --audit-log-maxbackup=1
    - --audit-log-maxsize=10
    - --audit-dynamic-configuration
    - --feature-gates=DynamicAuditing=true
    - --runtime-config=auditregistration.k8s.io/v1alpha1=true

Option2:
    - --audit-dynamic-configuration
    - --feature-gates=DynamicAuditing=true
    - --runtime-config=auditregistration.k8s.io/v1alpha1=true

Falco deployment command:

helm install falco --set auditLog.enabled=true --set auditLog.dynamicBackend.enabled=true falcosecurity/falco

Auditsink.yml:
# Source: falco/templates/auditsink.yaml
apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: falco
spec:
  policy:
    level: RequestResponse
    stages:
      - ResponseComplete
      - ResponseStarted
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
      service:
        namespace: default
        name: falco
        port: 8765
        path: /k8s-audit

**How to reproduce it**

Follow instructions on https://github.com/falcosecurity/charts/tree/falco-1.5.1/falco
**Expected behaviour**

K8s events should be visible in the Falco logs

**Screenshots**

**Environment**
NAME         STATUS   ROLES    AGE    VERSION
k8s-master   Ready    master   105d   v1.18.5
k8s-node1    Ready    <none>   105d   v1.18.5

- Falco version:

Falco: 0.26.1
Chart: 1.5.0
- System info:
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:
Helm chart

**Additional context**

**Comment by antoinedeschenes** [comment]
See #38
