### ISSUE TITLE
Small typo in values.yaml for OpsGenie apiKey

### ISSUE THREAD

**Issue by nhuray** [falcosecurity/charts#136]
Hi Falco charts maintainers,

I found a small typo in values.yaml for OpsGenie apiKey.

`aipKey` instead of `apiKey`

https://github.com/falcosecurity/charts/blob/dc90844d7a0e49a1c2f8b586c2b888460ec93598/falcosidekick/values.yaml#L120

Regards,

**Comment by Issif** [comment]
Hi @nhuray, thanks, I'll fix it soon.
I released a new version of falcosidekick few days ago and I've to update the chart for.

**Comment by KeisukeYamashita** [comment]
This PR(https://github.com/falcosecurity/charts/pull/141) solved it so you should be able to configure the API key with `apiKey` in `>=2.17.0` falcosidekick Helm chart release (cc: @Issif )

**Comment by leogr** [comment]
I can confirm it has been fixed.
Thank you!
/close
