### ISSUE TITLE
Falco rules are out of date

### ISSUE THREAD

**Issue by CyberHippo** [falcosecurity/charts#138]
**Motivation**

I am running falco using the [Helm chart](https://github.com/falcosecurity/charts/tree/master/falco).

It would be nice for the image `falcosecurity/falco` to be part of the list `falco_sensitive_mount_images` by default to prevent the following logs from appearing : 

```
{"output":"14:10:47.030309000: Notice Container with sensitive mount started (user=<NA> user_loginuid=0 command=container:27b5a30e6497 k8s.ns=default k8s.pod=falco-72l9n container=27b5a30e6497 image=falcosecurity/falco:0.26.2 mounts=[...]}
```

This issue seems related to [this issue](https://github.com/falcosecurity/falco/issues/1428) and it looks like [the rules](https://github.com/falcosecurity/charts/tree/master/falco/rules) from this `charts` repository are out of date with the [main falco repository](https://github.com/falcosecurity/falco/tree/master/rules).

**Feature**

It would be nice for the `falcosecurity/falco` image to be whitelisted by default in the list `falco_sensitive_mount_images` and for the [rules](https://github.com/falcosecurity/charts/tree/master/falco/rules) to be in sync with the rules of the [main falco repository](https://github.com/falcosecurity/falco/tree/master/rules).

A similar [fix](https://github.com/falcosecurity/falco/pull/1429) could be applied to this repository.

**Alternatives**

For now, I created a custom rules as follows : 

```yaml
- list: falco_sensitive_mount_images
  append: true
  items: [falcosecurity/falco]
```

**Comment by leogr** [comment]
We usually keep in sync the ruleset to the released Falco version.
Since those rule fixes have not been released yet, the chart does not yet include them.

I will update the whole ruleset as soon as the next Falco release (v0.27.0) comes out (planned for Dec 1st).

Btw, I can agree this process is not optimal. We're just using this releasing strategy to ensure that the whole ruleset works well with the corresponding Falco version.

**Comment by CyberHippo** [comment]
Hi @leogr ,

Thanks for the prompt answer ! No worries.
I can wait until the next release.

Thanks for all the great work on Falco btw, amazing tool.

**Comment by CyberHippo** [comment]
Hi @leogr, do you have any update on the next Falco release (v0.27.0) ? Thank you

**Comment by leogr** [comment]
As discussed during our community call, the next Falco release has been rescheduled for January 2020 (likely not before the 10th, but not yet confirmed).

**Comment by CyberHippo** [comment]
@leogr Great, thank you !
