### ISSUE TITLE
Allow use of existing secrets in sidekick chart

### ISSUE THREAD

**Issue by aywrite** [falcosecurity/charts#145]
**Motivation**

We manage our kubernetes deployments using a gitops workflow, in practice this means as much of our config as possible is checked into git. Currently this is difficult with the falco sidekick chart because the secrets for the various notifications backends have to be put in a `values.yaml` file. Although it is possible to encrypt this file etc, it forces a particular workflow rather than allowing us to use our normal workflow for managing kubernetes secrets. It would be useful if we could take care of managing the secrets in our own way and just point the sidekick chart to the appropriate secret.

**Feature**

Add an `existingSecret` value to the falco sidekick chart which if set would be referenced instead of the default secret which is created from the values passed to the `config` object. This is similar to how many other helm charts manage the same problem - for example see the `existingSecret` paramenters in https://github.com/bitnami/charts/tree/master/bitnami/postgresql.

**Alternatives**

Expose an helm parameter which allows injecting environment variables into the container which could be used to configure the secret values from an existing secret.

**Additional context**

I don't want to use helm secrets for our gitops workflow, I prefer to use something like bitnami sealded secrets or the sops-operator for managing encrypted secrets.

**Comment by Issif** [comment]
Hi @aywrite, thanks for your issue.

I totally agree, this is a point we need to address for improving security and allow gitOps flows. I'll try to address it asap.

**Comment by Issif** [comment]
If you feel OK, you can submit a PR too.

**Comment by Issif** [comment]
Existing secrets can be used since #163 so I'm closing this issue 👍
