### ISSUE TITLE
[falco-chart] falco-no-driver image by default

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#150]
**Motivation**

The `falcosecurity/falco-no-driver` container image ships Falco (statically linked build) without the building toolchain. Using that image has several pros:
- smaller image size
- less volume mount points
- attack surface reduced
- work either in "fully privileged" or "least privileged" (although the latter can have some caveats)

However, the image requires that the driver has already been installed by other means. Likely, the driver can either be already installed on the host or by using the `falcosecurity/falco-driver-loader` as an init container (the Falco chart supports [init containers](https://github.com/falcosecurity/charts/pull/89) yet).

Thus, I don't see any relevant cons to not use `falcosecurity/falco-no-driver` by default.

**Feature**

- add an init container with `falcosecurity/falco-driver-loader` by default (opt-out must be possible)
- use `falcosecurity/falco-no-driver` container image by default
- allow the chart to use either "fully privileged" or "least privileged" modes (fully privileged enabled by default since it ensures better compatibility)

N.B.
The above defaults will allow users to use the chart as before without any disruptions.

**Alternatives**

We could leave `falcosecurity/falco` image as the default and support the other case implicitly by providing a set of configuration options (like the `extraInitContainer`). This alternative is possible but requires much more effort for a user that wants to use the other image.

**Additional context**

We may need https://github.com/falcosecurity/charts/issues/147 to be implemented before.

**Comment by tspearconquest** [comment]
Greetings! Would it be possible to reopen this? This is a useful thing to have and we are setting it up based on the documentation currently at [#using-an-init-container](https://github.com/falcosecurity/charts/blob/master/falco/README.md#using-an-init-container)

Would it be helpful for me to submit a PR to copy this over to the falco.org docs in case this is never implemented?

**Comment by leogr** [comment]
> Greetings! Would it be possible to reopen this? This is a useful thing to have and we are setting it up based on the documentation currently at [#using-an-init-container](https://github.com/falcosecurity/charts/blob/master/falco/README.md#using-an-init-container)

AFAIK, running [falco-no-driver with falco-driver-loader as init container](https://github.com/falcosecurity/charts/blob/master/falco/README.md#using-falcosecuritydriver-loader-image) should work already.
But, it's the default option. 
What's your idea? Would like to have it as default?

**Comment by tspearconquest** [comment]
Hello,

Actually, what I was saying is that I think that page is less visible by being only on the helm chart repo, and that it would be more visible on falco.org itself, so I am interested in writing a PR to put the same details on falco.org. Would you accept a PR to do so?

That being said/asked, yes, it would be great if this was the default, as it is a smaller deployment when separated and may have better security overall because of the separation.

**Comment by leogr** [comment]
> Actually, what I was saying is that I think that page is less visible by being only on the helm chart repo, and that it would be more visible on falco.org itself, so I am interested in writing a PR to put the same details on falco.org. Would you accept a PR to do so?

The falco.org mostly includes documentation regarding artifacts that are considered official (as per [these definitions](https://github.com/falcosecurity/evolution#adoption-model). Unfortunately, our helm chart is formally still "incubating". For this reason, there's no such documentation regarding the chart on the website. 
On the other hand, if you would like to improve the documentation of the container images (which are "official"), I believe there will be no issue. 
In general, any proposal is always welcome :+1: And thank you for raising this topic.

Btw, we can continue this discussion here :point_down: 
https://github.com/falcosecurity/falco-website/issues/459
 

> That being said/asked, yes, it would be great if this was the default, as it is a smaller deployment when separated and may have better security overall because of the separation.

I have nothing against that. We just have to understand what the community thinks as it is an important change for users.

**Comment by tspearconquest** [comment]
Great, thank you for considering it.

How does the community get awareness of this effort and provide feedback?

**Comment by leogr** [comment]
> Great, thank you for considering it.
> 
> How does the community get awareness of this effort and provide feedback?
> I think slack would be the right place to move forward with discussing this effort?

You're welcome!

Slack for sure. Also, the [community calls](https://github.com/falcosecurity/community#falco-community-calls).

**Comment by sotoiwa** [comment]
Hi. [#using-an-init-container](https://github.com/falcosecurity/charts/blob/master/falco/README.md#using-an-init-container) guides how to load the initialization container driver, but the helm chart has set `privileged: true` in [the security context](https://github.com/falcosecurity/charts/blob/master/falco/templates/daemonset.yaml#L59) of the falco/falco-no-driver container. I want to minimize the capability etc. required for the falco-no-driver container, but there is no option in the chart parameters to customize the security context.
