### ISSUE TITLE
CI TODOs

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#156]
**Motivation**

Just a reminder for this [comment](https://github.com/falcosecurity/charts/pull/154#issuecomment-737798867) by @cpanato 

**Feature**

- [x] add the required GitHub status in prow (see https://github.com/falcosecurity/test-infra/blob/master/config/config.yaml#L82)
- [x] replace the lint to use the CT tool instead of the helm lint, the CT test more things

**Alternatives**

**Additional context**

**Comment by cpanato** [comment]
for `add the required GitHub status in prow` PR: https://github.com/falcosecurity/test-infra/pull/240

**Comment by cpanato** [comment]
for ` replace the lint to use the CT tool instead of the helm lint, the CT test more things` : https://github.com/falcosecurity/charts/pull/158

**Comment by cpanato** [comment]
this is done
/close
