### ISSUE TITLE
Icon in falco chart is to 404 page

### ISSUE THREAD

**Issue by mattfarina** [falcosecurity/charts#192]
**Describe the bug**

The icon in the falco chart points to https://falco.org/images/logos/falco-logo.png. This is now a 404 not found page. It worked back in January but no longer works.

**How to reproduce it**

Go to https://falco.org/images/logos/falco-logo.png and you will see a 404 not found page.

This impacts display in places that show information about the falco chart. Such as https://artifacthub.io/packages/helm/falcosecurity/falco. Notice the falco logo is no longer used and a generic image is used.

**Expected behaviour**

The icon to point to a working image location.

**Comment by Issif** [comment]
It's related to the recent refactoring of website cc @fntlnz
