### ISSUE TITLE
Falco not able to build driver module

### ISSUE THREAD

**Issue by shashwat-sec** [falcosecurity/charts#195]
**Falco not able to load driver module. Getting the below error:** 

``````
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 4.14.209-160.339.amzn2.x86_64, if present
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/falco_amazonlinux2_4.14.209-160.339.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Sun Feb 21 15:35:19 2021: Falco version 0.25.0 (driver version ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7)
Sun Feb 21 15:35:19 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Sun Feb 21 15:35:19 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Sun Feb 21 15:35:20 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Sun Feb 21 15:35:21 2021: Unable to load the driver.
Sun Feb 21 15:35:21 2021: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
``````

**AWS EKS 1.18
   OS Image: Amazon Linux 2
   Kernel version: 4.14.209-160.339.amzn2.x86_64**

- Falco version:
Falco version 0.25.0

**Comment by leogr** [comment]
You need to update Falco to the latest version since the prebuilt repository has been moved to https://download.falco.org/
Alternatively, if you wanted to stick with Falco 0.25.0 you can manually set the env var `DRIVERS_REPO` to `https://download.falco.org/`

N.B.:
It has been changed since Falco 0.26.2, you can find more detail here :point_down: 
https://falco.org/blog/falco-0-26-2/

**Comment by irivera007** [comment]
Im seeing similar issue with version 0.27.0, installing using helm, still unable to download the driver
`Info
2021-02-22 13:58:28.231 CST* Trying to download prebuilt module from https://download.falco.org/driver/5c0b863ddade7a45568c0ac97d037422c9efb750/falco_cos_4.14.150%2B_1.ko
Error
2021-02-22 13:58:28.414 CSTMon Feb 22 19:58:28 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Error
2021-02-22 13:58:28.426 CSTcurl: (22) The requested URL returned error: 404
Error
2021-02-22 13:58:28.427 CSTDownload failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Error
2021-02-22 13:58:28.439 CSTMon Feb 22 19:58:28 2021: Falco version 0.27.0 (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)
Error
2021-02-22 13:58:28.439 CSTMon Feb 22 19:58:28 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Error
2021-02-22 13:58:28.439 CSTMon Feb 22 19:58:28 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Error
2021-02-22 13:58:29.311 CSTMon Feb 22 19:58:29 2021: Unable to load the driver.`

**Comment by irivera007** [comment]
What worked for me was to enable ebpf, setting that to true, resolved the download issue, seems like for version .27 we need to enabled that for GKE.

**Comment by leogr** [comment]
> What worked for me was to enable ebpf, setting that to true, resolved the download issue, seems like for version .27 we need to enabled that for GKE.

Enabling ebpf is always required for GKE: https://falco.org/docs/getting-started/third-party/production/#gke
But, it seems to be not related to the issue reported by @shashwat-sec

**Comment by shashwat-sec** [comment]
@leogr Installing kernel-devel utilities on the node worked for me.

`yum -y install kernel-devel-$(uname -r)`

**Comment by leogr** [comment]
> @leogr Installing kernel-devel utilities on the node worked for me.
> 
> `yum -y install kernel-devel-$(uname -r)`

:+1: 
That works too since by doing so the script is able to compile the driver, and no need of downloading the prebuilt one.
