### ISSUE TITLE
Add support for pod annotations on falco-exporter daemonset

### ISSUE THREAD

**Issue by nonamef** [falcosecurity/charts#201]
**Motivation**
Using Victoria Metrics vmagent and it requires annotations on pods that are scraped.

**Feature**
Add support for additional annotations same as https://github.com/helm/charts/pull/22086/commits/b153279d120a8f652883c14e204e1422a8d97b45.

Just need to add the lines:
#charts/falco-exporter/templates/daemonset.yaml
      {{- if .Values.daemonset.annotations }}
      annotations:
        {{ toYaml .Values.daemonset.annotations | nindent 8 }}
      {{- end }}

#charts/falco-exporter/values.yaml
   podAnnotations: {}

**Comment by leogr** [comment]
Hi @nonamef 

Would you like to open a PR for that?

**Comment by sergeyshaykhullin** [comment]
Also using victoria metrics

/remove-lifecycle stale

**Comment by leogr** [comment]
Actually fixed by https://github.com/falcosecurity/charts/pull/289
