### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [falcosecurity/charts#223]
**Motivation**

Hello,

In order to combat dockerhub's imposed rate limits it would be great to update the helm charts to default to the ECR registry for the Docker images.

**Additional context**

https://kubernetes.slack.com/archives/CMWH3EH32/p1620308542378000

**Comment by onedr0p** [comment]
Looks like we are still missing a tagged version on

https://gallery.ecr.aws/falcosecurity/falcosidekick-ui

**Comment by leogr** [comment]
@falcosecurity/charts-maintainers any thoughts on this?

**Comment by cpanato** [comment]
we can push to ghcr as well

**Comment by leogr** [comment]
We are already pushing all images to https://gallery.ecr.aws/falcosecurity
(basically, we are  _de facto_ supporting ECR, since the CI in Falco takes care of that).

**Comment by onedr0p** [comment]
Looks like we are still missing a tagged version on

https://gallery.ecr.aws/falcosecurity/falcosidekick-ui

There's only latest

**Comment by Issif** [comment]
> Looks like we are still missing a tagged version on
> 
> https://gallery.ecr.aws/falcosecurity/falcosidekick-ui
> 
> There's only latest

You're right, I'll fix it asap
