### ISSUE TITLE
Pagerduty config in charts not matching with Sidekick commit related to Issue#197

### ISSUE THREAD

**Issue by rahulroy1** [falcosecurity/charts#233]
Hi,
As per Issue#197 (https://github.com/falcosecurity/falcosidekick/issues/197) and related commit https://github.com/falcosecurity/falcosidekick/pull/200/commits,
the latest PagerDuty handler code uses only "RoutingKey", instead of the earlier set of config parameters like `apiKey`, `service` etc.

However, in the values.yaml present in the Helm repo (https://github.com/falcosecurity/charts/tree/master/falco), still the old config parameters for PagerDuty are there and the new `RoutingKey` is not referred.

As a result, setting RoutingKey using
`--set falcosidekick.config.Pagerduty.RoutingKey=` doesn't show PagerDuty as the output for Sidekick.

**Expected behavior**
The Helm repo for falcosecurity/charts/sidekick should have the latest config parameter - `RoutingKey `

**Comment by Issif** [comment]
Hello, 

I forgot this issue for a while, sorry. The configuration has been updated now, the `RoutingKey` value is now available. See: https://github.com/falcosecurity/charts/blob/18b9a6b986f4cb4547ffa79900e351dafbfd695d/falcosidekick/values.yaml#L229

Regards,
