### ISSUE TITLE
Does this chart replace the helm/stable chart?

### ISSUE THREAD

**Issue by frankreno** [falcosecurity/charts#24]
Hi Folks:

I am a PM at Sumo Logic and we package Falco with our chart for collecting data from K8s.  I wanted to confirm that this is the chart that will replace the chart in helm/stable.  We plan to migrate to this chart to get the fix for #10 which is not in helm/stable.  We also want to confirm if there have been any significant changes between `1.1.7` of the helm/stable chart and this chart (e.g. changes to the behavior of the chart, etc).

**Comment by leogr** [comment]
Hi @frankreno 

I confirm that [this chart](https://github.com/falcosecurity/charts/tree/master/falco) replaces the chart in helm/stable (that's in the process of [being deprecated](https://github.com/helm/charts/pull/22481)).

Basically, the chart in helm/stable was copied over here, then it was updated to `1.1.8`. You can also find the changelog between `1.1.7` and `1.1.8` [here](https://github.com/falcosecurity/charts/blob/master/falco/CHANGELOG.md#v118). 

The `1.1.8` does not introduce significant changes other than the #10, and the Falco version bumped to `0.23.0`.

I hope I have answered your questions :)

**Comment by frankreno** [comment]
@leogr this is exactly what I needed, thanks much!

**Comment by leogr** [comment]
You are welcome!

Btw, I keep this issue open until we clarify it within the documentation, in case other people are looking for the same question :)

/kind documentation

**Comment by leogr** [comment]
Since the old chart has been removed from `helm/stable` and our README has been updated, I believe we can finally close this issue.
