### ISSUE TITLE
allow for specifying custom arguments to falco-driver-loader

### ISSUE THREAD

**Issue by travisghansen** [falcosecurity/charts#259]
**Motivation**

I have scenarios where clusters do not have outbound internet access. The container sits indefinitely trying to download the file and eventually gets restarted due to liveness/readiness checks. I prefer to bypass the attempt to download the driver altogether and just let it build (ie: force `--compile`).

**Feature**

Perhaps in the entrypoint script do something like this? `/usr/bin/falco-driver-loader ${CUSTOM_DRIVER_LOADER_ARGS}`

**Alternatives**

Introduce `env` vars native to the `falco-driver-loader` which allow locking in the behavior?
Place a timeout on the code that tries to download the file (should probably be done anyway, but having a way to force to not even attempt is even better).

**Additional context**

**Comment by leogr** [comment]
I believe that needs to be addressed in Falco first :point_down: 
https://github.com/falcosecurity/falco/blob/master/docker/falco/docker-entrypoint.sh#L30

Another alternative might be to use the init container approach :point_down: 
https://github.com/falcosecurity/charts/tree/master/falco#using-falcosecuritydriver-loader-image
I have never tried, but it should allow passing any argument to the `falco-driver-loader` image.

**Comment by travisghansen** [comment]
Yes the timeout should be handled in falco directly.

Thanks for the pointer on the init container. That looks like a viable option so I’ll give it a whirl.
