### ISSUE TITLE
[falcosidekick] Upgrade Ingress to networking.k8s.io/v1

### ISSUE THREAD

**Issue by sboschman** [falcosecurity/charts#273]
**Describe the bug**

In k8s 1.22 the [currently used](https://github.com/falcosecurity/charts/blob/master/falcosidekick/templates/ingress.yaml#L4) API version for the falcosidekick Ingress resource is [removed](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122). As of k8s 1.22 deploying the chart fails.

**Comment by Issif** [comment]
This is a fair point, we'll keep both versions with a condition, we need to still allow people to run the ingress for cluster < 1.19.

Thank you for the issue, what ETA do you need for?
