### ISSUE TITLE
falcosidekick httpOutput.url configmap issue 

### ISSUE THREAD

**Issue by mmonitz** [falcosecurity/charts#280]
1. falco and falcosidekick generate service name based on fullname helper template:
https://github.com/falcosecurity/charts/blob/770a308d6203a04de640bce16eadcddc4d2c30fd/falcosidekick/templates/_helpers.tpl#L18-L22 
(in most cases .Release.Name-.Chart.Name-falcosidekick)
in some cases when using falco chart as requirement for a master chart and supplying falcosidekick.enabled=true , Chart.Name may be different for the falco and falcosidekick templates. causing httpOutput.url to be not match the generated service name
2. https://github.com/falcosecurity/charts/blob/770a308d6203a04de640bce16eadcddc4d2c30fd/falco/templates/configmap.yaml#L195 gives prevents a simple workaround to first issue by ignoring httpOutput.url variable when using falcosidekick.enabled=true 
httpOutput.url should override the generated value from falcosidekick to allow workarounds

**Comment by mmonitz** [comment]
This issue is follow up from chat with @Issif https://kubernetes.slack.com/archives/CMWH3EH32/p1633331438498300

**Comment by Issif** [comment]
This is a use-case I didn't checked before, sorry. I'll figure out how to solve this.

**Comment by mac-chaffee** [comment]
/remove-lifecycle stale

Still relevant. My revision number for my helm chart is greater than 100 at this point, and I've had to manually edit the configmap to move the extra "-falco" every time. I have a link to this issue in my NOTES.txt to remind me :)

**Comment by mac-chaffee** [comment]
/remove-lifecycle stale 

163 deploys now, one of these days I'll get tired of editing the configmap manually after a `helm upgrade` and fix this, but I'm a little pressed for time at the moment
