### ISSUE TITLE
falcosidekick: sign and verify artifacts with keyless approach using cosign

### ISSUE THREAD

**Issue by developer-guy** [falcosecurity/charts#303]
**Motivation**

To make these artifacts (binaries, container images, checksums) more secure. So, we can use cosign to sign them, after then verifying them to prove that any of these have not been tampered with. 

**Feature**

There are different ways of achieving this. But, IMHO, the most elegant and secure way of doing this is a keyless approach which means that we do not even need to store public/private keys somewhere, instead, we can use a transparency log (Rekor) as a source of the truth for our proof. 

**Alternatives**

**Additional context**

cc: @cpanato @Issif @dentrax

**Comment by cpanato** [comment]
@developer-guy we are using circleci and afaik they does not offer the oidc token to use :(

**Comment by Issif** [comment]
Hello, we all agree this is a feature we need to have. @cpanato already worked on the setup, we should have everything ok for next week. This topic is related to falcosidekick itself, not the helm chart, please, create this issue in related repo.
