### ISSUE TITLE
Update helm values with PolicyReport support

### ISSUE THREAD

**Issue by r0binak** [falcosecurity/charts#307]
Helm charts have old helm values, policy report output not install

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Issif** [comment]
The creation of Policy Reports is now available in [Falcosidekick 2.25.0](https://github.com/falcosecurity/falcosidekick/releases/tag/2.25.0), you can follow [this guide](https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report/falco-adapter) to install the CRD for. The Helm chart is up to date to use the latest version of Falcosidekick

**Comment by Issif** [comment]
It should be ok now, with an `helm upgrade`, I updated the Falco chart yesterday and it has been merged around 9:30pm

**Comment by leogr** [comment]
Has this been fixed already?

@Issif @r0binak

**Comment by r0binak** [comment]
> Has this been fixed already?
> 
> 
> 
> @Issif @r0binak 

yes
