### ISSUE TITLE
Missing comma in k8s_audit_rules.yaml

### ISSUE THREAD

**Issue by eelkonio** [falcosecurity/charts#318]
A comma is missing in the list "allowed_kube_namespace_image_list"

Without the comma, yaml parsing will be incorrect and may combine two items into one.

The comma should be present at line 291 (after "k8s.gcr.io/addon-resizer")

**Environment**

- Falco version:
Falco Helm charts 1.17.4 (latest)
- System info:
irrelevant

**Comment by Kaizhe** [comment]
@eelkonio do you mind to create a quick fix for this problem ?
