### ISSUE TITLE
Falco chart NOTES.txt points to the wrong url

### ISSUE THREAD

**Issue by Daklon** [falcosecurity/charts#332]
**Describe the bug**

NOTES.txt on falco chart has the following url for falcosidekick chart: https://github.com/falcosecurity/charts/falcosidekick

The problem is that this url is wrongly build and points to nowhere. Github answers with a 404

**How to reproduce it**

Go to https://github.com/falcosecurity/charts/falcosidekick

**Expected behaviour**

Navigate to the master branch, on the falcosidekick directory

**Screenshots**
![Captura de pantalla de 2022-05-17 19-06-07](https://user-images.githubusercontent.com/5181367/168870854-43262c11-f950-4e50-89c9-055fac0b05a3.png)

**Environment**

- Falco version: Not applicable

- System info: Not applicable

- Cloud provider or hardware configuration: Not applicable
- OS: Not applicable

- Kernel: Not applicable

- Installation method: Helm chart

**Additional context**

**Comment by Issif** [comment]
Hello,

Thanks for these report. I'm working on a new version of the chart for falcosidekick and I'll update the dependency in falco chart after, I'll fix this at this time.

**Comment by leogr** [comment]
Fixed by #333, so I'm closing this. Thank you @Daklon 
/close
