### ISSUE TITLE
Falco helm chart priorityClassName value

### ISSUE THREAD

**Issue by enmuro** [falcosecurity/charts#376]
**Describe the bug**

When configuring priorityClassName on Falco helm chart there's a divergence between values.yaml name and templates/pod-template.yaml.

[In values.yaml](https://github.com/falcosecurity/charts/blob/falco-2.0.4/falco/values.yaml#L44)
podPriorityClassName:

[In templates/pod-template.tpl](https://github.com/falcosecurity/charts/blob/falco-2.0.4/falco/templates/pod-template.tpl#L30)
{{- if .Values.priorityClassName }}
  priorityClassName: {{ .Values.priorityClassName }}
{{- end }}

**How to reproduce it**

**Expected behaviour**

values.yaml and pod-template.yaml should have the same value name.

**Screenshots**

**Environment**

- Falco version: falco-2.0.4

- System info: N/A

- Cloud provider or hardware configuration: N/A
- OS: N/A

- Kernel: N/A

- Installation method: Kubernetes

**Additional context**

**Comment by alacuku** [comment]
Hi @enmuro, thanks for spotting it! Are you willing to open a PR and fix it? It would be a nice contribution from your side! Let me know what do you think and if you need any help!
