### ISSUE TITLE
Deployment Falco Pods may not need to be run as root (e.g. in the K8s audit plugin usecase)

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/charts#377]
**Motivation**

With the introduction of the new Falco plugin system and the new 2.X Helm charts, it's not always really required to run the Falco pod as root. Nevertheless, Falco still does this which could often violate security policies (PSP, OPA, etc.).

**Feature**

I think it would make sense to introduce a flag which allows one to configure (or simply override?) the used service user from root to something else.
I think we could even by default set the user to `UID 1000` whenever the syscall event source is disabled. Of course, I would still add a values.yaml flag to override this default behavior in case some plugins still have the requirement to run as root.

**Alternatives**

At the moment this could already be done via the following Helm values but there's probably a nicer way to do that automatically (as mentioned above, e.g. whenever the syscall event source is disabled):
```yaml
podSecurityContext:
  runAsUser: 1000
```

**Additional context**

Please let me know what you think about that. If you agree, I could create a PR in the near future.

Thanks & regards,
Philip

**Comment by leogr** [comment]
It looks like a good idea, but it may have some side effects (which I don't recall by heart).

@falcosecurity/deploy-kubernetes-maintainers and @falcosecurity/charts-maintainers wdyt?
also cc @alacuku

**Comment by zuc** [comment]
I like the idea and I can't remember of any other use case (apart from syscalls) where `root` is required, so +1 from me

**Comment by maxgio92** [comment]
Looks a good idea to me too.
Moreover, what about enabling also to select specific capabilities, still avoiding uid 0?

**Comment by alacuku** [comment]
We can write a helper that is evaluated when the syscall event source is disabled. Users can still overwrite the default behavior by setting the `podSecurityContext`.

**Comment by PhilipSchmid** [comment]
/remove-lifecycle stale

Will implement this in the next days. Sorry for the delay.

**Comment by PhilipSchmid** [comment]
Sorry I'm not using Falco anymore and I therefore won't implement this any time soon. If anybody wants to implement it, please feel free to take it over 😉 .
