### ISSUE TITLE
Update OWNERS

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/charts#4]
**Motivation**

Following up on https://github.com/falcosecurity/contrib/issues/12

We need to review and update the OWNERS file.

More importantly - we need to identify new owners for these charts. 

**Feature**

Calling all maintainers. If you are interested in maintaining or contributing to the chart please follow up below. 

I would also like to volunteer myself as a maintainer to help with ensuring features and support are not missed. 

**Alternatives**

**Additional context**

**Comment by cpanato** [comment]
I would like to help where is possible, I'm trying for quite some time, but don't have the time to attend the meetings

However I can help in the charts :-)

**Comment by leodido** [comment]
In this PR (https://github.com/falcosecurity/charts/pull/2) I setup people according to https://github.com/falcosecurity/contrib/issues/12

**Comment by zestrells** [comment]
If there’s anyway I can help maintain the Falco helm charts that would be awesome!

**Comment by nibalizer** [comment]
@zestrells @cpanato that's awesome that you're interested in helping maintain these charts! Thanks! We have some open issues that you can look at. If you'd like some 1:1 to discuss where to help I am on slack or we could schedule a call.

**Comment by leogr** [comment]
We still need help!

Btw, I think it's time to add @Issif to the `OWNERS` for falcosidekick :)

**Comment by leogr** [comment]
I believe it's all done now, so closing.
