### ISSUE TITLE
Add support for ARM for falcosidekick-ui chart

### ISSUE THREAD

**Issue by e-minguez** [falcosecurity/charts#406]
**Motivation**

As Falco supports ARM, I guess it would be nice for sidekick-ui to support ARM as well, and that includes the Redis dependency

**Feature**

Support ARM CPUs

**Alternatives**

Use sidekick with no UI

**Additional context**

**Comment by e-minguez** [comment]
Related to https://github.com/falcosecurity/falcosidekick-ui/issues/66

**Comment by e-minguez** [comment]
Related to https://github.com/RediSearch/RediSearch/issues/3110

**Comment by Issif** [comment]
I agree it could be nice, for falcosidekick-ui itself, it's not an issue and we can add ARM support. For redisearch, they don't provide an ARM image and you must know, I had to fork it to add TTL to keys, my PR to add it in the upstream is still waiting https://github.com/RediSearch/redisearch-go/pull/167

**Comment by j771** [comment]
Does Falco fully support ARM?
I am testing out running the daemonset on the latest k8s v1.23 EKS AMI and I am getting this error from the init container (image `docker.io/falcosecurity/falco-driver-loader:0.33.1`):
```
* Trying to download a prebuilt falco module from https://download.falco.org/driver/3.0.1%2Bdriver/aarch64/falco_amazonlinux2_5.4.228-131.415.amzn2.aarch64_1.ko
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco module
```

How often are these prebuilt falco module updated?

**Comment by Issif** [comment]
You can search for available prebuilt drivers here https://download.falco.org/driver/site/index.html

**Comment by samip5** [comment]
Okay, so according to the docker hub readme for `https://hub.docker.com/r/redislabs/redisearch` container is deprecated and one should look into replacing it with redis-stack container. Worth noting is that the redis-stack container is indeed multi-arch.

**Comment by Issif** [comment]
I tested the images from https://hub.docker.com/r/redis/redis-stack, everything seems OK. I need to do more tests to see if you can migrate without losing the data.
