### ISSUE TITLE
Helm chart fails to run on GKE - CrashLoopBackoff

### ISSUE THREAD

**Issue by lucascioffi-mb** [falcosecurity/charts#408]
**Describe the bug**

Installing the Helm chart on a cluster on GKE doesn't work. The Falco pods go on CrashLoopBackoff (but sidekick still works).

**How to reproduce it**

Falco was installed using the following command:
`helm install falco falcosecurity/falco --set ebpf.enabled=true --set falcosidekick.enabled=true --set falcosidekick.webui.enabled=true --namespace=falco --create-namespace`

**Expected behaviour**

Expected pods to run.

**Screenshots**
![image](https://user-images.githubusercontent.com/90479024/192894554-900552c2-69e1-427c-b3d8-e09bfd4caa3b.png)

**Environment**

- Falco version (helm show chart):

> apiVersion: v2
> appVersion: 0.32.2
> dependencies:
> - condition: falcosidekick.enabled
>   name: falcosidekick
>   repository: https://falcosecurity.github.io/charts
>   version: 0.5.9
> description: Falco
> home: https://falco.org
> icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/falco/horizontal/color/falco-horizontal-color.svg
> keywords:
> - monitoring
> - security
> - alerting
> - metric
> - troubleshooting
> - run-time
> maintainers:
> - email: cncf-falco-dev@lists.cncf.io
>   name: The Falco Authors
> name: falco
> sources:
> - https://github.com/falcosecurity/falco
> version: 2.0.18

- Cloud provider or hardware configuration:
GCP

- OS:

Container-Optimized OS with Docker (cos)
Nodes and Master running K8S version 1.22.12-gke.300	

- Installation method:

Helm Chart

**Additional context**

Logs from `kubectl logs falco-9qwzc -n falco --all-containers`:
(Seems like module's URL doesn't exist?)

> 
> * Setting up /usr/src links from host
> * Running falco-driver-loader for: falco version=0.32.2, driver version=2.0.0+driver
> * Running falco-driver-loader with: driver=module, compile=yes, download=yes
> 
> ================ Cleaning phase ================
> 
> * 1. Check if kernel module 'falco' is still loaded:
> - OK! There is no 'falco' module loaded.
> 
> * 2. Check all versions of kernel module 'falco' in dkms:
> - There are some versions of 'falco' module in dkms.
> 
> * 3. Removing all the following versions from dkms:
> 2.0.0+driver
> 
> - Removing 2.0.0+driver...
> 
> ------------------------------
> Deleting module version: 2.0.0+driver
> completely from the DKMS tree.
> ------------------------------
> Done.
> 
> - OK! Removing '2.0.0+driver' succeeded.
> 
> 
> [SUCCESS] Cleaning phase correctly terminated.
> 
> ================ Cleaning phase ================
> 
> * Looking for a falco module locally (kernel 5.10.127+)
> * Trying to download a prebuilt falco module from https://download.falco.org/driver/2.0.0%2Bdriver/x86_64/falco_cos_5.10.127%2B_1.ko
> curl: (22) The requested URL returned error: 404
> Unable to find a prebuilt falco module
> * Trying to dkms install falco module with GCC /usr/bin/gcc
> DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
> 
> Creating symlink /var/lib/dkms/falco/2.0.0+driver/source ->
>                  /usr/src/falco-2.0.0+driver
> 
> DKMS: add completed.
> * Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc)
> * Trying to dkms install falco module with GCC /usr/bin/gcc-8
> DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
> * Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc-8)
> * Trying to dkms install falco module with GCC /usr/bin/gcc-6
> DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
> * Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc-6)
> * Trying to dkms install falco module with GCC /usr/bin/gcc-5
> DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
> * Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc-5)
> * Trying to load a system falco module, if present
> Consider compiling your own falco driver and loading it or getting in touch with the Falco community
> Error from server (BadRequest): container "falco" in pod "falco-9qwzc" is waiting to start: PodInitializing

**Comment by alacuku** [comment]
Hi @lucascioffi-mb, starting from [version `2.0.0`](https://github.com/falcosecurity/charts/blob/master/falco/CHANGELOG.md#v200) of the helm chart the driver version is set as shown in the README: https://github.com/falcosecurity/charts/tree/master/falco#daemonset. In your case the adapted helm install command is:
```bash
helm install falco falcosecurity/falco --set driver.kind=ebpf --set falcosidekick.enabled=true --set falcosidekick.webui.enabled=true --namespace=falco --create-namespace
```
Let me know if it works!

**Comment by lucascioffi-mb** [comment]
Hi @alacuku!!!
It worked, thanks a ton.

May i suggest updating the documentation here to reflect this change?
https://falco.org/docs/getting-started/third-party/production/#gke
