### ISSUE TITLE
Improve k8saudit documentation for the Falco Chart

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#410]
**What to document**

See https://github.com/falcosecurity/falco/issues/2172#issuecomment-1249101560

/help

cc @alacuku

**Comment by alacuku** [comment]
Hey @leogr, I've added a step-by-step guide on how to set up a minikube environment with kubernetes audit logs enabled and how to deploy Falco with the k8s audit plugin. For more info: https://falco.org/docs/getting-started/third-party/learning/#falco-with-multiple-sources
Maybe we should add the link in the charts Readme.md under the k8s audit section.

**Comment by leogr** [comment]
@alacuku I believe this has been fixed. Do you confirm? If yes I will close
