### ISSUE TITLE
[falcosidekick-ui] able to configure redis ttl

### ISSUE THREAD

**Issue by ArgTang** [falcosecurity/charts#415]
**Motivation**

Current falco ui chart deployment will fill up redis instance diskspace because TTL option is not exposed in chart

**Feature**

a way to set TTL option for the sidekickui deployment. 

**Alternatives**

1. add a specific values.yaml prop to set the TTL value, 0 as default
2. add a generic way to set env variables to the deployment

**Comment by Issif** [comment]
The version of falcosidekick-ui which allows to manage the TTL for the keys is not yet released, this is why the helm chart doesn't expose the setting.

**Comment by Issif** [comment]
The v2.1.0 is out and the helm chart is updated
