### ISSUE TITLE
Support setting namespace metadata in values for falco

### ISSUE THREAD

**Issue by tra0x** [falcosecurity/charts#422]
**Feature**

Allow setting release namespace in `values.yaml` for falco. Solution must respect cli flags and not break existing implementations.

If there is support for this, I will happily open a PR and follow the contribution guidelines.

**Motivation**

Allow for declarative deployment practices to be followed with namespace metadata. Explicitly setting metadata in values or manifests should at least be an option available. 

**Alternatives**

Using an imperative style like `helm install falco falcosecurity/falco --namespace falco`.

**Comment by alacuku** [comment]
Hi @tra0x, could you provide a use case for why you need this?

**Comment by tra0x** [comment]
Use case is being able to completely define falco's deployment using its `values.yaml`. Ideally everything about a release is explicitly set there.

Contrasted with the current process, namespace is the only bit of configuration that must be stored somewhere else. Thus deploying requires `helm install falco falcosecurity/falco --values falco/values.yaml --namespace [some-other-source]`. Config being split into two sources adds a layer of complexity, especially in CICD.

An example project that offers this is [Prometheus' chart](https://github.com/prometheus-community/helm-charts/blob/3e10bac1441ffe3bab7f653256676a7d2081fb7a/charts/kube-prometheus-stack/values.yaml#L9).

**Comment by alacuku** [comment]
Thanks for the explanation, it's ok for me! I will happily review your PR if you are willing to contribute!
