### ISSUE TITLE
upgrade path

### ISSUE THREAD

**Issue by jhailsecurity** [falcosecurity/charts#430]
**What to document**
We are running the helm charts 1.16 for falco and falcosidekick 0.4.4. Is there an upgrade path to 2.x and .5.x?

**Comment by alacuku** [comment]
Hi @jhailsecurity, unfortunately not. Starting from release `3.0.0`, the [BREAKING-CHANGES](https://github.com/falcosecurity/charts/blob/master/falco/BREAKING-CHANGES.md) file documents the introduced breaking changes and upgrade path for each new release of the Falco charts.
