### ISSUE TITLE
missing kernel image

### ISSUE THREAD

**Issue by jhailsecurity** [falcosecurity/charts#431]
When deploying the falco version .30.0 it receives an error when deploying on a instance or no kernel found at the location it is directed to pull from. The ec2 instance is a amazonlinux 2 instance. 

* Running falco-driver-loader for: falco version=0.30.0, driver version=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.o
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco eBPF probe
* Trying to compile the eBPF probe (falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.o)
make[1]: *** /lib/modules/5.4.209-116.367.amzn2.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:20: all] Error 2
mv: cannot stat '/usr/src/falco-3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/bpf/probe.o': No such file or directory
Unable to load the falco eBPF probe
Wed Nov 16 18:51:44 2022: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Wed Nov 16 18:51:44 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Nov 16 18:51:44 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Nov 16 18:51:45 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed Nov 16 18:51:45 2022: Unable to load the driver.
Wed Nov 16 18:51:45 2022: Runtime error: can't open BPF probe '/root/.falco/falco-bpf.o': Errno 2. Exiting.``` 

**Environment**
AWS ECS on EC2 instance of amazon linux 2 

- Falco version:

- System info: .30

- Cloud provider or hardware configuration:AWS
- OS: amazon linux 2

- Kernel:

- Installation method:

ECS/helm
**Additional context**

**Comment by jhailsecurity** [comment]
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
it's using amazon linux 2, kernel 5.4.209-116.367

**Comment by bryanasdev000** [comment]
Related to https://github.com/falcosecurity/charts/issues/420 and https://github.com/falcosecurity/charts/issues/390.

No prebuilt available for this AMI for now. Check linked issues on how to procced.
