### ISSUE TITLE
Got CrashLoopBackOff status on pod creation

### ISSUE THREAD

**Issue by Ltrock** [falcosecurity/charts#439]
**Describe the bug**
I am using the upstream chart/falco/value.yaml with chart version: 2.2.0, but got this issue related to yaml-cpp plugin.
```
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.32.0, driver version=39ae7d40496793cf3d3e7890c9bbdc202263836b
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/39ae7d40496793cf3d3e7890c9bbdc202263836b/falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.o
* Skipping compilation, eBPF probe is already present in /root/.falco/falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.o
* eBPF probe located in /root/.falco/falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.o
* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o
Wed Jan  4 08:02:07 2023: Runtime error: Error reading config file(/etc/falco/falco.yaml): could not load plugins config: yaml-cpp: error at line 35, column 16: bad conversion. Exiting
```

**How to reproduce it**

**Expected behaviour**

Falco pod status is running

**Screenshots**

**Environment**

- Falco version: 0.33.0
- System info:
- Cloud provider or hardware configuration: 
- OS:
- Kernel:
- Installation method:

**Additional context**

**Comment by alacuku** [comment]
Hi @Ltrock, could you provide more info about the `values.yaml` file you are using? I deployed Falco using the default values:
```
helm install falco --set driver.kind=ebpf falcosecurity/falco --version=2.2.0
```
and not issues popped out.

**Comment by Ltrock** [comment]
Hi @alacuku Thank you so much for your reply. I also found that I made a mistake that my Chart is not updated to the 2.2.0 version. Now, the chart is up-to-date and it triggers the new deployment without any error. I'll close it.
