### ISSUE TITLE
Error helm install falcosidekick (chart 0.5.10)

### ISSUE THREAD

**Issue by lepsusx** [falcosecurity/charts#441]
**Describe the bug**

Error helm install falcosidekick 

```
helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
```
```
helm install falcosidekick falcosecurity/falcosidekick --set webui.enabled=true
Error: INSTALLATION FAILED: YAML parse error on falcosidekick/templates/deployment-ui.yaml: error converting YAML to JSON: yaml: line 36: could not find expected ':'
```
or
```
helm install falco falcosecurity/falco --set falcosidekick.enabled=true --set falcosidekick.webui.enabled=true -n falco
Error: INSTALLATION FAILED: YAML parse error on falco/charts/falcosidekick/templates/deployment-ui.yaml: error converting YAML to JSON: yaml: line 36: could not find expected ':'
```

**Environment**

- Falco version:
```
NAME                                    	CHART VERSION	APP VERSION                       	DESCRIPTION
falcosecurity/falco                     	2.4.5        	0.33.1                            	Falco                                             
falcosecurity/falco-exporter            	0.9.1        	0.8.0                             	Prometheus Metrics Exporter for Falco output ev...
falcosecurity/falcosidekick             	0.5.10       	2.27.0                            	Connect Falco to your ecosystem   
```                
- System info:

Kubernetes v1.23.6
containerd.io 1.5.11
helm v3.10.3
- Cloud provider or hardware configuration:
- OS: Ubuntu 20.04 LTS

- Kernel:
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Linux k8sdemreprod1001 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:

From source
**Additional context**
I have not found the minimum requirements and I know helm in a basic way, additionally I tried with another namespace.

**Comment by ckotzbauer** [comment]
Same here, there is a space missing for the new args from the ui-deployment:
```yaml
```

**Comment by Issif** [comment]
I'm fixing right now

**Comment by Issif** [comment]
@lepsusx @ckotzbauer if you use directly the falcosidekick chart, it's fixed, if you use the falco one, it will be in few minutes. sorry.

**Comment by ckotzbauer** [comment]
Thanks @Issif!
This fix worked, but I discovered another bug: The 2.1.0 image of falcosidekick was released without the "v" prefix. https://hub.docker.com/r/falcosecurity/falcosidekick-ui/tags

**Comment by Issif** [comment]
It's not a bug, it's like that since the beginning, I thought it wasn't mandatory in semver method and I started without and I think it's better for the users to no change that.

**Comment by ckotzbauer** [comment]
> It's not a bug, it's like that since the beginning, I thought it wasn't mandatory in semver method and I started without and I think it's better for the users to no change that.

But then the "v" has to be removed from this chart. Otherwise the image can't be pulled.

**Comment by Issif** [comment]
Sorry, I thought we were talking about sidekick and not the ui. Let me check.

**Comment by Issif** [comment]
@ckotzbauer the image with the `v` tag is pushed on Dockerhub https://hub.docker.com/layers/falcosecurity/falcosidekick-ui/v2.1.0/images/sha256-8d6c2f8b93e3a38c5d7728c9b6f2c9d3b99264de54e014eb5d5cd271c3e646ad?context=explore

And the healthcheck endpoint is now unauthenticated

**Comment by ckotzbauer** [comment]
Thanks @Issif for your very quick response. I'll appreciate that!

**Comment by Issif** [comment]
I'm happy you use my projects, your feedback is really valuable to me. Thanks.

**Comment by Issif** [comment]
@lepsusx is that ok for you? can you close this issue when it is please

**Comment by lepsusx** [comment]
it's ok, thanks @Issif !!
