### ISSUE TITLE
falcosidekick: Big int provided to .webui.ttl leads to invalid formatting

### ISSUE THREAD

**Issue by trallnag** [falcosecurity/charts#457]
Related to already fixed issue <https://github.com/falcosecurity/charts/issues/454>.

The value `.webui.ttl` expects integer and not string.

```yaml
webui:
  ttl: 0
```

But internally this must be converted to string. This was fixed as part of <https://github.com/falcosecurity/charts/issues/454>.

Now there is a problem left if `.webui.ttl` is really big. The integer is rendered with power notation.

```yaml
webui:
  ttl: 72592000
```

This leads to render with scientific notation.

```yaml
args:
- "-t"
- "7.2592e+07"
```

And error.

```
invalid value "2.592e+06" for flag -t: parse error
```

The simplest solution would be to make `.webui.ttl` a string instead of integer.

Or we add conversion to template.

```
{{ .Values.webui.ttl | quote }}
```

becomes

```
{{ .Values.webui.ttl | int | quote }}
```

Currently workaround is to simply provide `.webui.ttl` as string instead of integer.

@Issif

**Comment by Issif** [comment]
Hi,

I understand your point, but I don't see it like a real issue.

72592000s means 840 days. It's really huge (I know the time filter goes up to 2y, but I'm not even sure the javascript will be able to display that duration without crashing your browser).

If you need a real long time retention, take a look at the other Falcosidekick outputs (Elasticsearch, S3, eg). When I created Falcosidekick-UI the purpose was to offer a nice way to see latest and real time events without installing a complex stack. The v1 didn't had any storage, all events were kept in memory, with max 200 events. We loosed everything after each restart of the pod. I did the v2 with a redis backend to offer more flexibility to adopters and reduce the load in the browser as all full text searches are made in the backend now.

If you need long term retention and you're sure you will not fill the PVC in few days (like some users did), set 0 as TTL, it means no expiration.

I hope I'm clear, we can discuss about on Slack if you need.
