### ISSUE TITLE
[Falco chart] Containerd and Crio socket paths passed as hardcoded values to Falco container

### ISSUE THREAD

**Issue by alacuku** [falcosecurity/charts#468]
**Describe the bug**

The chart allows configuring the socket path for `containerd` 
https://github.com/falcosecurity/charts/blob/4c138561e773cb011bec62b96e943d6d2c22b8b1/falco/values.yaml#L241-L245
and `crio` runtimes
https://github.com/falcosecurity/charts/blob/4c138561e773cb011bec62b96e943d6d2c22b8b1/falco/values.yaml#L247-L251

Those values are not templated at all:
https://github.com/falcosecurity/charts/blob/4c138561e773cb011bec62b96e943d6d2c22b8b1/falco/templates/pod-template.tpl#L75-L82 

**How to reproduce it**
Set the paths for the mentions container runtimes to custom values and install Falco. The deployed pod does not use those values.

**Expected behaviour**

The config values set by the user should be passed to the Falco container.

**Comment by ReddaHawk** [comment]
Hi @alacuku i can do it if you want

**Comment by ReddaHawk** [comment]
Hi,

After some analysis I found that the values you mentioned before are correctly used in the Volumes section to configure the hostPath path, as shown below:
https://github.com/falcosecurity/charts/blob/4c138561e773cb011bec62b96e943d6d2c22b8b1/falco/templates/pod-template.tpl#L275-L289

If you agree the issue can be closed.

**Comment by alacuku** [comment]
Thanks @ReddaHawk !
