### ISSUE TITLE
Crashloopbackoff state

### ISSUE THREAD

**Issue by Shifna12Zarnaz** [falcosecurity/charts#485]
When using 'helm install falco falcosecurity/falco --namespace falco --create-namespace' ..getting crashloopback off state.When installing through ebpf driver,'helm install falco falcosecurity/falco --set driver.kind=ebpf --namespace falco --create-namespace'  with this command pod is running ,but am not able to see the falco inside the etc but am able to see the falcorules.yaml inside var/lib/docker ....folder structure but not as etc/falco/falcorules and also when giving falco command ....getting an error as  falco command is not working

**Comment by alacuku** [comment]
By default, the chart uses the `kernel module`. It could be that the `driver-loader` init container is not able to download/compile a kernel module for your system. 
Could you please post the logs of the `falco-driver-loader` init container?

**Comment by Shifna12Zarnaz** [comment]
Initially I used kind cluster.But after using minikube ,am getting  as ..."./var/lib/docker/volumes/minikube/_data/lib/docker/overlay2/477a78551cb7ed8d86ad15daf5d2265a07662d467f0d4990697b241aeedf1b8b/diff/etc/falco" this is my folder structure..only here am able to see my falcorules.yaml and when giving falco command am getting as no command found.Kindly help me in solving this issue as soon as possible

**Comment by alacuku** [comment]
Have a look here: https://falco.org/docs/getting-started/third-party/learning/#minikube. There is everything you need to know in order to run falco on minikube.

**Comment by Shifna12Zarnaz** [comment]
Using minikube cluster and
when trying to install falco through helm with the below command
helm install falco falcosecurity/falco --set driver.kind=ebpf --namespace falco --create-namespace
my pod is in running state....But in devcluster or anyother cluster,when trying to install falco with this command getting crash loopbackoff state.Pls help me to solve this issue

**Comment by alacuku** [comment]
Could you please share the logs of `falco` and `falco-driver-loader` containers?
