### ISSUE TITLE
Error: INSTALLATION FAILED: template: falco/templates/service.yaml:1:14

### ISSUE THREAD

**Issue by sgilaniz** [falcosecurity/charts#492]
Getting the following error installing falco in EKS cluster 
"Error: INSTALLATION FAILED: template: falco/templates/service.yaml:1:14: executing "falco/templates/service.yaml" at <.Values.auditLog.enabled>: nil pointer evaluating interface {}.enabled" 
Please let me know how to get past this. 
Thanks.

**Comment by sgilaniz** [comment]
Hey I am using Falco version: 3.1.1  with kubernetes version 1.26 . The only changes Ive made to the Values.yaml file are 

http_output:
    enabled: true
   url: "http://my-sidekick-falcosidekick:2801/"
   user_agent: "falcosecurity/falco"

driver:
  enabled: true
  kind: module

  json_output: true

**Comment by alacuku** [comment]
Please make sure that you are using the `values.yaml` file from the version of the same chart you are installing. In this case, the `values.yaml` file shipped with the chart `3.1.1`.

**Comment by sgilaniz** [comment]
Thank you I was able to do a fresh install without an error

**Comment by alacuku** [comment]
Feel free to close this issue.
