### ISSUE TITLE
Centralise FalcoSidekick UI 

### ISSUE THREAD

**Issue by msalman899** [falcosecurity/charts#493]
Hello, is there any way to setup centralize Sidekick UI and configure all of deployed falco/sidekick agents across different cluster to point to single UI.

I am deploying falco to several clusters and wondering if its possible to have a central UI to review all of falco events from all clusters.

**Comment by PaulPowershell** [comment]
hi, i think it's already possible with change value of configmap in falco values L822
  http_output:
    # -- Enable http output for security notifications.
    enabled: false
    # -- When set, this will override an auto-generated URL which matches the falcosidekick Service.
    # -- When including Falco inside a parent helm chart, you must set this since the auto-generated URL won't match (#280).
    url: ""

ex :
http_output:
  enabled: true
  url: http://falco-falcosidekick.falcosecurity.svc.cluster.local:2801
