### ISSUE TITLE
Falco-Exporter pods failing on Kubernetes

### ISSUE THREAD

**Issue by ZuzkaP** [falcosecurity/charts#508]
After installing falco on version 3.2.1. and enabling grpc and grpc output (no Mtls), I have tried to install Falco-exporter 0-9-6 with grafanadashboard and serviceMonitor enabled. Both are placed together in the Falco namespace.

Unfortunately the exporter pods are Crashing with the message : gRPC: error dialing server: context deadline exceeded 

![image](https://github.com/falcosecurity/charts/assets/11503387/b24a7724-9c42-4dcf-aeb5-b2870bdd082d)

![image](https://github.com/falcosecurity/charts/assets/11503387/33e5d6d8-40ab-49ee-b0df-6e3467db3c10)

- Falco version:
3.2.1

- Cloud provider or hardware configuration:
- OS:
- 
AWS/Linux

- Installation method:
Helm/kubernetes

**Comment by ZuzkaP** [comment]
we solved our problem by  --set driver.kind=ebpf

**Comment by afreyermuth98** [comment]
Hello @ZuzkaP I got the same issue as you, can you give me what values do you give to the falco-exporter chart please ?
