### ISSUE TITLE
Unable to set the password for Redis

### ISSUE THREAD

**Issue by fricka676** [falcosecurity/charts#519]
Hello,

I am using the command 

'helm install falco falcosecurity/falco \
 --set tty=true \
 --set falcosidekick.enabled=true \
 --set falcosidekick.webui.enabled=true \
 --set falcosidekick.webui.redis.storageClass="manual"  \
 --set falcosidekick.webui.user="admin:xxx"  \
 --set falcosidekick.config.googlechat.webhookurl=http://xxxx \
 --namespace falco'

 to install Falco and Falcosidekick, 
but I found that the Redis created in this way does not have a password by default, which is dangerous after all. 
So I tried using '

helm install falco falcosecurity/falco \
 --set tty=true \
 --set falcosidekick.enabled=true \
 --set falcosidekick.webui.enabled=true \
 --set falcosidekick.webui.redis.storageClass="manual"  \
 --set falcosidekick.config.redis.password="xxx"  \
 --set falcosidekick.webui.user="admin:xxx"  \
 --set falcosidekick.config.googlechat.webhookurl=http://xxxx \
 --namespace falco

', but still failed.

So is there a problem with my operation, or is there a problem that hasn't been resolved

**Comment by Issif** [comment]
HI,

The helm chart has been updated to allow to specify a password but nothing has been yet implemented to start the redis pod with. I'll work on that asap.

**Comment by fricka676** [comment]
So, I can understand that at this stage, we cannot solve this problem and need to wait for updates, right
