### ISSUE TITLE
Cannot use "outputs" field in helm chart

### ISSUE THREAD

**Issue by Ca20009** [falcosecurity/charts#520]
I am using falco with helm and want to set the "outputs" as to restrict the rate that falco can produce alerts. This feature is documented in the normal falco.yaml here:

# With the default settings, the throttling mechanism is disabled.
outputs:
  rate: 0
  max_burst: 1000

This does not seem to be in the helm chart, and if you put it into the helm chart under falco, it does not seem to be picked up

download falco helm chart
changed values.yaml

######################
# falco.yaml config  #
######################
falco:

  outputs:
   rate: 1
   max_burst: 1000

install the helm chart, check pod logs - no mention of the restricted outputs

Fri Aug 18 13:14:24 2023: Falco version: 0.35.1 (x86_64)
Fri Aug 18 13:14:24 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Fri Aug 18 13:14:24 2023: Loading rules from file /etc/falco/falco_rules.yaml
Fri Aug 18 13:14:24 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Fri Aug 18 13:14:24 2023: Starting health webserver with threadiness 2, listening on port 8765
Fri Aug 18 13:14:24 2023: Loaded event sources: syscall
Fri Aug 18 13:14:24 2023: Enabled event sources: syscall
Fri Aug 18 13:14:24 2023: Opening 'syscall' source with Kernel module

Helm chart should respect the outputs

**Environment**

- Falco version:

- System info: 0.35.1 (x86_64)

- Cloud provider or hardware configuration:
- OS: VERSION="18.04.6 LTS (Bionic Beaver)"

- Kernel: 

- Installation method: Helm

**Additional context**

**Comment by Andreagit97** [comment]
ei thank you for reporting! we will take a look!

**Comment by alacuku** [comment]
hi @Ca20009, the issue should be fixed in #525

**Comment by Andreagit97** [comment]
I will close this, feel free to reopen if this is still an issue!

/close
