### ISSUE TITLE
Setting up liveness and readiness probes on falco

### ISSUE THREAD

**Issue by blame19** [falcosecurity/charts#53]
**Motivation**
As part of Kubernetes' best practices, I'd like to set Readiness and Liveness probes on all the containers deployed on my infrastructure. As of now, the chart lacks this capability.

**Feature**

At the moment Falco doesn't define any probe. We'd like to have a way to check if the container is running correctly; this is a bit challenging since it's not clear what we could check to ensure falco's is up.

**Alternatives**

Possible ways to ensure Falco is running would be:

- Checking on running processes inside the container
- Checking on logs/files used by falco

Any option would be welcome.

**Comment by cpanato** [comment]
/reopen
i will work on that
