### ISSUE TITLE
Resource limits are difficult to override downstream if the limits are removed in a downstream config.

### ISSUE THREAD

**Issue by nvo-aurora** [falcosecurity/charts#531]
**Motivation**

Default resource limits being set upstream in this chart makes it difficult to override downstream. 
We have removed CPU limits in our config, however the below setting in values.yaml

```
  limits:
    cpu: 1000m
```
cannot be overridden if our config has no CPU limits set, and so this setting gets retained in our final deployment.

**Feature**

Would it be possible to remove these default limits or could you give us other options/alternatives to work around these default limits?

**Alternatives**

We can possibly set a limitrange in our namespace and just not set a maximum so that it could override the default limits, but I'm not sure how feasible that is in our current setup.

**Additional context**

This relates to https://github.com/falcosecurity/falco/issues/1403 specifically with the debug option to remove CPU resource limits as a potential remediation.

**Comment by nvo-aurora** [comment]
Would a config with the below override the default setting in values.yaml?
```
limits:
  cpu: ''
```
And remove the cpu limit?

**Comment by alacuku** [comment]
> Default resource limits being set upstream in this chart makes it difficult to override downstream. We have removed CPU limits in our config, however the below setting in values.yaml
> 
> ```
>   limits:
>     cpu: 1000m
> ```
> 
> cannot be overridden if our config has no CPU limits set, and so this setting gets retained in our final deployment.

Hi @nvo-aurora, you need to set a new value in your configuration file (values.yaml) in order to overwrite the default values. 
In this case, you will need to set the whole `resources`:
```yaml
resources:
  limits:
    cpu: 
```

This will overwrite the resources for you deployment.

**Comment by nvo-aurora** [comment]
A blank value like the below would not work, correct?  We need a number value?
  cpu: ''

**Comment by alacuku** [comment]
Hi @nvo-aurora, a blank value like this would work:
```yaml
resources:
  limits:
    cpu: 
```
