### ISSUE TITLE
About "one click" stopping services

### ISSUE THREAD

**Issue by fricka676** [falcosecurity/charts#532]
Hello,

Attempting to deploy Falco in our production environment

However, our operations team raised a question,

Assuming that our k8s cluster has some issues that need to be investigated,

We need to stop Falco's service on a node machine,

To confirm that the problem is not caused by Falco

I did not find any relevant information in the document description

Is Falco not equipped with this feature, or did I not find it,

How to operate it in this scenario

**Comment by alacuku** [comment]
Hi @fricka676, not sure what you mean by "one click" stopping service, but since you are running in k8s the best way would be to `cordon` the node under investigation and remove services as you need.

**Comment by fricka676** [comment]
The operation of stopping the Falco service

To rule out that the K8S issue is not caused by Falco

**Comment by alacuku** [comment]
There is no such need when running falco in a container. As said before, just stop the falco container running on the node.

**Comment by fricka676** [comment]
How to stop the pod on a node machine separately

Manually stop, theoretically the pod will restart

**Comment by Issif** [comment]
@fricka676 Your question is not related to Falco itself, it is more a question about the administration of a Kubernetes cluster.

The main purpose of Kubernetes is to manage the lifecycle of applications, and ensure you they are up and running. It's possible anyway to "block" that behavior for a specific node, this is exactly what @alacuku proposed and I agree 100%.

Basically, by "cordon" a node, you tell the scheduler to not start new pods on it. By then terminating the falco pod, it will not reappear. Here's a blog post I found explaining the process and more: https://medium.com/@mehmetodabashi/administrating-kubernetes-clusters-how-to-drain-and-cordon-nodes-804e5b1a6e1d

**Comment by fricka676** [comment]
Okay, thank you very much for your answers. I'll study it
