### ISSUE TITLE
Falco support for ECS Fargate

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/charts#539]
We want to use falco charts for AWS ECS Fargate. Is the feature rolled out now.
https://sysdig.com/blog/falco-support-on-aws-fargate/

**Comment by Andreagit97** [comment]
Right now we don't support Fargate, i think we are all waiting for the BPF support in Fargate -> https://github.com/aws/containers-roadmap/issues/1027

**Comment by ajinkya1986** [comment]
Thank you @Andreagit97  for the prompt response
