### ISSUE TITLE
sidekick: AWS IRSA + default secret fails.

### ISSUE THREAD

**Issue by jan-g** [falcosecurity/charts#541]
**Describe the bug**

The `config.aws.rolearn` setting is overloaded in an unfortunate fashion, which prevents falco-sidekick from working using IRSA with a minimal role, and the helm-chart provided configuration secret.

The problem here is that by setting `config.aws.rolearn`, we *already* trigger the "assume a specified role" behaviour when creating an AWS client in the falco-sidekick code.

However, because the same setting also causes the serviceAccount to be annotated with an IRSA key, EKS will *automatically* inject environment variables that cause the AWS SDK to generate a client that's *already* adopted the role on creation. [This is the correct behaviour]

At that point, the code here: https://github.com/falcosecurity/falcosidekick/blob/master/outputs/aws.go#L66-L85 uses the adopted role and attempts to re-adopt the role. The code unfortunately swallows the underlying error, but the reported error here is typically somethiing ilke:
```
User: arn:aws:sts::123412341234:assumed-role/your-role-name/1695816822677266000 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123412341234:role/your-role-name
```

... and sure enough, it's not wrong.

The problem here is that, if you rely on the helm chart to generate the falco-sidekick configuration secret, this line: https://github.com/falcosecurity/charts/blob/master/falcosidekick/templates/secrets.yaml#L89 unconditionally puts AWS_ROLEARN into the environment, and thus into the configuration. That triggers this double-role-assumption misbehaviour.

**Non-fix..?**

An obvious thing is to remove the offending line from the generated secret; but since there may be other deployments that use alternative credential injection and attempt to escalate to the role via those, they would be broken by such a move.

Alternatively, if `config.aws.rolearn` is there *solely* to support IRSA, then this approach would be simple and achieve that goal.

**Potential fixes**

Either: introduce a `config.aws.irsa-role-arn` (spelling of your choice) and use *that* to annotate the serviceAccount,
or: introduce something like `config.aws.irsa` which, if true (the proposed default), (a) annotates the serviceAccount using config.aws.rolearn (iff present), and (b) prevents AWS_ROLEARN from appearing in the secret.

This would preserve existing behaviour in almost all cases - but fix it. People can opt into or out of IRSA (which is frankly a neater and more contained option to prevent arbitrary pods on the same node spamming cloudwatch logs, for instance) and the default bare-bones helm chart will work.

**How to reproduce it**

Deploy the helm chart without `config.existingSecret` set in an IRSA-enabled environment, specifying `config.aws.rolearn`.

**Expected behaviour**

The sidekick should "just work". Specifically: the serviceAccount should be correctly annotated, and the container should not see AWS_ROLEARN in its environment.

**Mitigation**

The existing broken behaviour can be worked around by creating a secret that mirrors the chart-created one, but without AWS_ROLEARN in it, and using `config.existingSecret` to point to it.

**Environment**

AWS, EKS, IRSA enabled for the serviceAccount target role.

(This is with 2.28.0 and the corresponding charts.)

**Comment by jan-g** [comment]
Incidentally if anyone can clarify the intended use of rolearn, I'll prep a patch for this myself. I *suspect* it's supposed to be an IRSA thing only, because the current serviceAccount annotation is otherwise unconditional. If that's true then just dropping it from secret.yaml will suffice.

**Comment by Issif** [comment]
Thank for that report, I confirm your right, the current implementation for the IRSA is not correct, I'll fix that.

I'll introduce a new value `config.aws.useIrsa`, if true, then the `config.aws.rolearn` will be used to set the annotations of the serviceAccount and not the secret value. wdyt?

FYI, the `aws.roleArn` has been implemented to allow falcosidekick to switch to a role, it's valuable for people running it outside EKS, only its usage in the Helm chart is not optimal.

**Comment by jan-g** [comment]
That makes a lot of sense; I think it's a quitable approach. Cheers!

**Comment by Issif** [comment]
Here's the PR #542

**Comment by Issif** [comment]
The falco chart has been updated, use the 3.8.2 to fix this issue.
