### ISSUE TITLE
Abandon CircleCI in favor of github actions

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/charts#543]
**Motivation**

All the falcosecurity org moved to github actions, retiring CircleCI.

**Feature**

Move the repo away from CircleCi.

**Alternatives**

None

**Additional context**

None

**Comment by FedeDP** [comment]
@cpanato you were willing to help if i remember correctly :) 

/assign @cpanato @FedeDP

**Comment by cpanato** [comment]
yes, working on that :)

**Comment by FedeDP** [comment]
Thank you! :)

**Comment by leogr** [comment]
I guess most of the work is done here. @cpanato we just need to update some docs, then I guess we can close this :partying_face:
