### ISSUE TITLE
Container information

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/charts#551]
Currently all the rules in falco have `%container.info` field in the output parameters, which populates only limited container information. Is it possible to add more container information for the rule which require them. Like `container.image`, `container.image.id`, `container.type`, `container.image.tag` etc

**Comment by alacuku** [comment]
Hi @ajinkya1986, it's not related to the charts. It's more a rule's customization. Please have a look here: https://github.com/falcosecurity/rules. If you still have trouble with how to customize the rules, please open an issue on the rules repository.
