### ISSUE TITLE
Unable to set password for WebUI

### ISSUE THREAD

**Issue by lacioffi** [falcosecurity/charts#553]
Even when setting the ` falcosidekick.webui.user` variable, the user for the webui is still `admin:admin`.

**How to reproduce it**

I configured Falco on a clean, test cluster with:

```
helm install falco -n falco --set driver.kind=ebpf --set tty=true falcosecurity/falco \
--set falcosidekick.enabled=true \
--set falcosidekick.webui.enabled=true \
--set falcosidekick.webui.user="something:another"
```

Afterwards, the credential is still set as "admin:admin"

**Expected behaviour**

The credential should be what i set in the `falcosidekick.webui.user` variable

**Screenshots**

Credential still set to admin:admin:
![image](https://github.com/falcosecurity/charts/assets/18557205/b898af63-4705-44c3-bb75-11f6998e09ff)

But Helm values set another credential: (dummy creds, don`t worry)
![image](https://github.com/falcosecurity/charts/assets/18557205/d3262079-0b20-4684-ae17-bfbb2ddab850)

**Environment**

- Falco version:
Falco version: 0.36.1 (x86_64)

- System info:
```
{
  "machine": "x86_64",
  "nodename": "falco-phc52",
  "release": "5.15.109+",
  "sysname": "Linux",
  "version": "#1 SMP Fri Jun 9 10:57:30 UTC 2023"
}
```
- Cloud provider or hardware configuration:

I'm running a GKE cluster (standard, not autopilot) on GCP. Just one node, nothing special.

- OS:

Google CoS (Container Optimized OS) for the GKE node.
As follows for the container itself:
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

The secret inside kubernetes DOES have the new user:
![image](https://github.com/falcosecurity/charts/assets/18557205/942f7e73-9dfe-4d1b-b068-5d1b90f6ede7)
![image](https://github.com/falcosecurity/charts/assets/18557205/e42c0f13-18c2-4178-9423-0fe5bd78e4d0)
![image](https://github.com/falcosecurity/charts/assets/18557205/2387c93d-1e65-47ca-80bf-096b0a42b114)

Also, the pod seems to be pointing to the secret:
![image](https://github.com/falcosecurity/charts/assets/18557205/19a42409-3c59-4a73-8fd5-9a3d889e71e2)

Maybe the secret name isn`t correctly mapping to the environment variable that it should? 

- Kernel:
```Linux falco-phc52 5.15.109+ #1 SMP Fri Jun 9 10:57:30 UTC 2023 x86_64 GNU/Linux```

- Installation method:
Helm Chart (https://artifacthub.io/packages/helm/falcosecurity/falco)

**Additional context**

None so far.

**Comment by Issif** [comment]
This is issue has been fixed in the chart 0.7.2 for falcosidekick, but the dependency the falco chart has not been updated yet. I was waiting for the merge of #542 first.

**Comment by Issif** [comment]
The falco chart has been updated, use the 3.8.2 to fix this issue.

**Comment by lacioffi** [comment]
Thank you!
