### ISSUE TITLE
Extra args not working as expected

### ISSUE THREAD

**Issue by avramenkovladyslav** [falcosecurity/charts#581]
**Describe the bug**
When I'm providing extra arguments `falco -t "custom_rules"` for Falco to work only with one type of alerts it's not working, still getting all alerts from default rules

**How to reproduce it**
Helm values:
```
falco:
  grpc:
    enabled: true
  grpc_output:
    enabled: true
  http_output:
    enabled: true
    url: "http://falco-falcosidekick.falco.svc.cluster.local:2801"
extra:
  args:
    - falco -t "custom_rules"
falcosidekick:
  enabled: true
  config:
    debug: true
    slack:
      outputformat: fields
      messageformat: '*{{ .Rule }}* on *{{ index .OutputFields "k8s.pod.name" }}*'
customRules:
  rules-shell.yaml: |-
    - rule: Terminal shell
      desc: Detects when a pod tries to request external shell
      condition: >
        k8s.ns.name = "default" and
        container.id != host and
        evt.type = execve and
        (proc.pname = bash or
        proc.pname = sh) and
        proc.cmdline != bash
      output: Terminal shell in
        (pod_name=%k8s.pod.name
        container_name=%container.name)
      priority: EMERGENCY
      tags: [custom_rules]

```

**Expected behaviour**

Only one message should appear

**Environment**

- Falco version: **Helm** 3.8.5, **falco** 0.36.2 (latest)

- System info:
```
  "machine": "x86_64",
  "nodename": "falco-8f48l",
  "release": "5.10.198-187.748.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Tue Oct 24 19:49:54 UTC 2023"
```

- Cloud provider or hardware configuration: AWS EKS
- OS: Debian GNU/Linux 12

- Kernel: ```Linux falco-8f48l 5.10.198-187.748.amzn2.x86_64 #1 SMP Tue Oct 24 19:49:54 UTC 2023 x86_64 GNU/Linux```

- Installation method: Kubernetes Helm

**Additional context**

My goal was to disable default rules as it's described in [documentation](https://github.com/falcosecurity/falco-website/blob/master/content/en/docs/rules/controlling-rules.md)

**Comment by alacuku** [comment]
Hi @avramenkovladyslav, is this still an issue?
