### ISSUE TITLE
Why ImagePullPolicy is default as Always

### ISSUE THREAD

**Issue by NingPekin** [falcosecurity/charts#59]
Hi,
I am seeing ImagePullPolicy is configured as Always for `nats`, `sns` and `pubsub `
https://github.com/falcosecurity/charts/blob/master/falco/templates/daemonset.yaml#L145
https://github.com/falcosecurity/charts/blob/master/falco/templates/daemonset.yaml#L154
https://github.com/falcosecurity/charts/blob/master/falco/templates/daemonset.yaml#L179

Could you please elaborate if there is any specific reason for it? If not, can we use param instead?

**Comment by leogr** [comment]
I guess because of `:latest`. 

Anyway, I agree to parameterize those values. Feel free to open a PR, if you'd like.

**Comment by leogr** [comment]
This issue does not apply anymore, since those integrations have been removed by #123
