### ISSUE TITLE
Create helm repository

### ISSUE THREAD

**Issue by nibalizer** [falcosecurity/charts#6]
There is a procedure for creating an index and helm repository for our charts. We should do it.

- [x] Create Repository and Assets
- [x] PR remove from helm/charts
- [x] PR in repository to helm/hub
- [ ] Setup chart testing [tool](https://github.com/helm/chart-testing)

**Comment by leogr** [comment]
Closed in favor of https://github.com/falcosecurity/charts/issues/58
