### ISSUE TITLE
How to replace falco_rules.yaml file when I use helm chat?

### ISSUE THREAD

**Issue by zein9** [falcosecurity/charts#600]
I'm using helm chat to install falco in my k8s environment. When I try to find a way to edit falco rules, I only find a guidance about add custom rules. I don't find a way to raplace the hold falco_rules.yaml file. 
I download newest falco_rules.yaml to k8s master under "/root/falco/rules.d/" and edit it. Then I try to edit my hem chat file as below, I get error log in falco about I must specify at least one rule file/directory in falco.yaml. May I know what's wrong with my testing?

==========cat helm chat yaml file=======
<img width="668" alt="image" src="https://github.com/falcosecurity/charts/assets/99779929/4be621f6-bb8f-4225-93aa-2785d23d1404">
=========end of cat helm chat yaml file======

====error log for falco pod========
root@demo-192-168-60-20:~/falco# kubectl logs falco-w6xzf -n falco -c falco
Fri Jan  5 02:05:57 2024: Falco version: 0.36.2 (x86_64)
Fri Jan  5 02:05:57 2024: Falco initialized with configuration file: /etc/falco/falco.yaml
Error: You must specify at least one rules file/directory via -r or a rules_file entry in falco.yaml
====end of error log for falco pod========

**Comment by leogr** [comment]
Have you deployed the Helm chart with default options?

If so, the rulesfiles artifacts are managed by `falcoctl` :point_down: and automatically downloaded from the upstream repo.
https://github.com/falcosecurity/charts/blob/6e5332eb6ca9dde8d1fdced90b30ae40c8a39198/charts/falco/values.yaml#L404-L430

If you want to provide your own custom `falco_rules.yaml` just for testing purposes, you should disable the automatic update from `falcoctl` first, then you can disable `/etc/falco/falco.yaml` and load your file via custom rules
