### ISSUE TITLE
Falcosidekick: allow custom labels/annotations on deployment objects

### ISSUE THREAD

**Issue by davejab** [falcosecurity/charts#602]
**Motivation**
The falcosidekick does not support adding custom labels/annotations to deployment objects. It would be useful to allow this so we can label/annotate to our needs.

**Feature**

Provide and option in chart values for specifying either common labels/annotations for all resources or specific labels/annotations for each resource.

**Alternatives**

There are no ways to set labels/annotations without directly editing the chart or using another tool to mutate the objects.

**Additional context**

The [falco](https://github.com/falcosecurity/charts/blob/6e5332eb6ca9dde8d1fdced90b30ae40c8a39198/charts/falco/values.yaml#L141) chart allows custom annotations on the daemonset. A similar implementation would be suitable.

**Comment by Issif** [comment]
Since the v0.8.0 of the Falcosidekic chart, annotations and labels can be added to the resources.
