### ISSUE TITLE
falco chart: removal of service account template from the chart version 4.0.0

### ISSUE THREAD

**Issue by CarpathianUA** [falcosecurity/charts#612]
Hi there,

I wondered why a service account template was removed from the chart version 4.0.0? A lot of people use service account with IRSA IAM role binding e.g. for `falcoctl` to pull custom rules artifacts from AWS ECR. 

Falco version: 3.7.0
Cloud provider or hardware configuration: AWS EKS 1.29
Installation method: Helm chart, version 4.0.0

**Comment by alacuku** [comment]
Hi @CarpathianUA, the reason why we removed the service account is noted here: https://github.com/falcosecurity/charts/blob/master/charts/falco/BREAKING-CHANGES.md#k8s-collector.

Can you get Falco to work in your environment using the default service account?

**Comment by CarpathianUA** [comment]
@alacuku Hi, thanky you for reply. Yeah, I can use a namespace's default or custom one. The only thing that it adds a level of inconvenience to chart usage is that I need to create or modify a service account outside of the chart. Maybe it makes sense to bring back the SA template to the chart with RBAC  (rb / crb) as well, to allow users to use them for their needs?

**Comment by alacuku** [comment]
Each namespace has a default service account. You don't need to create a new one for your use case. Furthermore, the rb/crb were static templates, without the possibility of being modified through the `values.yaml` files. Only the service account had some options, see below:
```bash
serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Annotations to add to the service account.
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
```
So my question is, did you modify the the SA, RB and CRB for your use cases? 
Before bringing them back, I want to be sure that they are needed. The only use case for Falco was the k8s client that is not anymore present.

**Comment by CarpathianUA** [comment]
@alacuku 
Usage of a default service account is possible, but not preferable to me, it's not flexible imho. Having an opportunity to use SA with or without CR/CRB, fully templated and optional within a chart is more like a useful feature for users for their specific needs - it just simplifies a deployment approach as well as k8s objects management, especially in GitOps-based environments. E.g. to deploy Falco in my case I need next - first to define and create non-default SA with e.g. Kustomize, and only after that deploy a Helm chart.

Since the `serviceAccount` and `serviceAccountName` parameters were deleted from the pod template in the latest version of the chart, the only way for me now is to use a default service account with custom annotations for the IAM IRSA role etc.  It also leads to lower security considerations, since any pod in a namespace can use a default service account without explicitly referring to it in the pod template.

**Comment by alacuku** [comment]
@CarpathianUA, the PR is merged. Can we close this issue?

**Comment by CarpathianUA** [comment]
Hi @alacuku
Thank you, I think yes. I'll test a new chart release a little bit later, but PR changes look good to me!
