### ISSUE TITLE
Error: parse error at (falco/templates/_helpers.tpl:406): unclosed action

### ISSUE THREAD

**Issue by jobinmat** [falcosecurity/charts#635]
Getting this error while installing falco 

```
helm install falco falcosecurity/falco \
>     --create-namespace \
>     --namespace falco
```
Error: parse error at (falco/templates/_helpers.tpl:406): unclosed action

**Comment by jobinmat** [comment]
`helm install falco falcosecurity/falco --set driver.kind=modern-ebpf`

I tried this as well but same error

**Comment by alacuku** [comment]
Hi @jobinmat, what is your helm version?

**Comment by alacuku** [comment]
The issue is related to formatting in helpers. I  opened a PR which changed the formatting and fixed the issue.
