### ISSUE TITLE
Fix for additional labels for falco-exporter servicemonitor

### ISSUE THREAD

**Issue by rcompos** [falcosecurity/charts#64]
**Describe the bug**

When deploying falco-exporter Helm chart with servicemonitor.additionallabels in values.yaml, the chart fails unless the value is a string, in which case the label is not created.

**How to reproduce it**

Edit values.yaml and add some servicemonitor additionallabels as map value(s).

```
serviceMonitor:
  # Enable the deployment of a Service Monitor for the Prometheus Operator.
  enabled: true
  additionalLabels:
    release: prom
```

```
⇒ helm upgrade --install falco-exporter . -f values.yaml -n falco
Error: UPGRADE FAILED: YAML parse error on falco-exporter/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
```

**Expected behaviour**

The additionallables should be created in the servicemonitor.  In this case "release: prom".

```
⇒ kctl -n falco get servicemonitors falco-exporter -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
  labels:
  ...
    release: prom
  ...
```

**Screenshots**

N/A

**Environment**

- Falco version:
Falco version: 0.24.0
Driver version: 85c88952b018fdbce2464222c3303229f5bfcfad

- System info:

- Cloud provider or hardware configuration:
GCP GKE Kubernetes v1.16.12

- OS:
  "machine": "x86_64",
  "nodename": "gke-yolo-infra-dev-default-node-pool-4754cdf8-1s69",
  "release": "4.19.112+",
  "sysname": "Linux",
  "version": "#1 SMP Thu May 21 12:32:38 PDT 2020"

- Installation method:
Helm chart

**Additional context**

**Here is the fix:**

File: falco-exporter/templates/servicemonitor.yaml
see lines 8-10 under metadata.labels.

```
{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "falco-exporter.fullname" . }}
  labels:
    {{- include "falco-exporter.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - port: metrics
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "falco-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
```

**Comment by leogr** [comment]
Hi @rcompos 

Good catch!

Could you open a PR to fix it?

**Comment by rcompos** [comment]
I tried to open a PR but I don't have the privileges.  Thanks!
