### ISSUE TITLE
error result from redis for GroupBy priority from falco-falcosidekick-ui-xxx pod

### ISSUE THREAD

**Issue by Jana-Ravi** [falcosecurity/charts#651]
**Describe the bug**

In my falcosidekick-ui-xxx pod I'm getting error log as below

2024/04/10 09:39:55 [INFO] : user 'admin' authenticated
2024/04/10 09:39:56 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:39:56 [ERROR]: code=400, message=error result from redis for GroupBy priority
2024/04/10 09:40:03 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:40:03 [ERROR]: code=400, message=error result from redis for GroupBy priority
2024/04/10 09:40:13 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:40:13 [ERROR]: code=400, message=error result from redis for GroupBy priority
2024/04/10 09:40:23 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:40:23 [ERROR]: code=400, message=error result from redis for GroupBy priority
2024/04/10 09:40:33 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:40:33 [ERROR]: code=400, message=error result from redis for GroupBy priority
2024/04/10 09:40:43 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:40:43 [ERROR]: code=400, message=error result from redis for GroupBy priority
2024/04/10 09:40:53 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:40:53 [ERROR]: code=400, message=error result from redis for GroupBy priority
2024/04/10 09:41:03 [ERROR]: error result from redis for GroupBy priority
2024/04/10 09:41:03 [ERROR]: code=400, message=error result from redis for GroupBy priority

**How to reproduce it**

I installed it using below command

helm install falco /home/admin1/charts/charts/falco --set falcosidekick.enabled=true --set falcosidekick.webui.enabled=true --set falcosidekick.webui.user=admin:xxxxxxxxx --set tty=true -n falco 

Because of this error I cannot be able to browse  falcosidekick UI URL. So can you guys please guide me about that error.

![image](https://github.com/falcosecurity/charts/assets/166608311/a7e95ace-0ca3-4fc4-9b83-aa0fdfc86a45)

**Comment by Issif** [comment]
This is a strange error. Can you try to delete the redis pod and its pvc, then restart the UI pod please. Something wrong might happened when the index has been created.

**Comment by Jana-Ravi** [comment]
Thanks, but no luck after deleting PVC and restarted redis pod. Just 2 mins my FalcoUI worked. After that my UI went down.
![image](https://github.com/falcosecurity/charts/assets/166608311/d59cb1e0-eba1-46e4-92ac-0e1f0abaef26)

Below I'm attaching my SC and PVC yaml content

![image](https://github.com/falcosecurity/charts/assets/166608311/7eea02b5-9c8e-4554-add7-457e184913a2)
![image](https://github.com/falcosecurity/charts/assets/166608311/b7058900-780e-486c-9b61-ebbc2dbfd8c0)

My PVC is below

![image](https://github.com/falcosecurity/charts/assets/166608311/9aa864fd-6dc9-42ab-be0b-79b859e823d5)

![image](https://github.com/falcosecurity/charts/assets/166608311/0090c450-24f0-468c-9b3b-249d93879828)

**Comment by Issif** [comment]
Can you try without a PVC by adding `--set falcosidekick.webui.redis.storageEnabled=false`?

**Comment by Jana-Ravi** [comment]
Thanks for your constant help @Issif 

yes, working fine after I disabled PVC storage for Redis. But for Prod like environment this pod's ephemeral storage is not best practice, because whenever my pod restart data will be erased. (Correct me I'm wrong)

Also, in my Storage class I'm using provisioner as "kubernetes.io/no-provisioner" this may cause any issue? Any suggestions please.

**Comment by Issif** [comment]
Did you try by specifying the SC at the installation with `--set falcosidekick.webui.redis.storageClass=local-storage`? I never try a local storage class by the docs also specify the bindingMode should be `WaitForFirstConsumer`:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

Just a guess.

FYI, Falcosidekick-UI has been initially developed to have "nice" overview of the triggered rules to show in my talks, the project grew a lot and allow now to know which ones to customize them before connecting Falco to a third party like your on-call system or else. The fact the UI became so popular and used in production still make me amazed.

**Comment by Jana-Ravi** [comment]
Hi @Issif   using Redis pod local storage my Falcosidekick UI is working fine. But I'm seeing some strange things in my application.
Approximately after 12 hours or 1 days I'm seeing my falco UI is not accessible. I didn't see any error logs in Pods. Only strange is my state of connection to 2802 port have "CLOSE_WAIT" response.

![image](https://github.com/falcosecurity/charts/assets/166608311/8e22f8ba-3065-4571-8f4f-6569aa951772)

Not sure this is something I need to check with my infra-Team or anything application level we need to troubleshoot. Always looking for your help.
