### ISSUE TITLE
Falcosidekick's WebHook connector ignores WEBHOOK_CUSTOMHEADERS env variable

### ISSUE THREAD

**Issue by PrettySolution** [falcosecurity/charts#658]
**Describe the bug**
Falcosidekick's WebHook connector ignores `WEBHOOK_CUSTOMHEADERS` env variable in falco-falcosidekick pod, resulting in an error in the logs: **WebHook - 415 Unsupported Media Type**

I've installed Falco Chart version **4.2.4** and made sure to configure all the necessary values for the `falcosidekick.config.webhook` object. Additionally, I've set up `falcosidekick.config.webhook.customHeaders`. Upon inspecting the environment variables within the falco-falcosidekick pod using the `env` command, I confirmed that the `WEBHOOK_CUSTOMHEADERS` environment variable is properly set with the `content-type:application/json`. 

Even after configuring the webhook headers correctly, I'm still encountering a **415 Unsupported Media Type** error in the logs.

**How to reproduce it**
install falco chart 4.2.4, enable falcosidekick and set up webhook connector
check logs in falco-falcosidekick Pod: Webhook - Unexpected Response  (415)

set falcosidekick.enabled = true
set falcosidekick.config.webhook.address = http://xxx.yyy.194.126:10029/falco
set falcosidekick.config.webhook.method = POST
set falcosidekick.config.webhook.checkcert = false
set falcosidekick.config.webhook.customHeaders = content-type:application/json

**Expected behaviour**

Falcosidekick - Post OK (200)

**Screenshots**
<img width="1412" alt="Screenshot 2024-04-18 at 19 37 16" src="https://github.com/falcosecurity/charts/assets/57800300/d5cd25c6-8152-4b8a-9d95-6ec10f907584">
<img width="1208" alt="Screenshot 2024-04-18 at 19 41 16" src="https://github.com/falcosecurity/charts/assets/57800300/2e363c42-f8e7-469c-bcf9-5856b4d97276">

**Environment**

- Falco version:
4.2.4

- Cloud provider or hardware configuration:
AWS: EKS
- Installation method:
helm chart

**Additional context**

**Comment by Issif** [comment]
Hi,

What was finally the issue and how did you solve it? Could be useful if others face the same. Thanks
