### ISSUE TITLE
Add OTEL Traces configuration

### ISSUE THREAD

**Issue by Jeansen** [falcosecurity/charts#669]
**Motivation**

The OTEL configuration from falcosidekick is missing in this chart.

**Feature**

Add https://github.com/falcosecurity/falcosidekick/blob/master/docs/outputs/otlp_traces.md to chart/values

**Additional context**

Maybe there is a reason why OTEL traces cannot be configured via Helm values.yaml. If they are simply not yet implemented, I'd be happy to create a PR.

**Comment by Issif** [comment]
The OTEL output in Falcosidekick will be part of the upcoming v2.29, this is why it's not already in the helm chart. For the release, I'll create all the values and communicate.

**Comment by Issif** [comment]
The release with the OTEL Traces is out and the helm chart has been updated for.
