### ISSUE TITLE
Grafana dashboard for new Falco metrics introduced in 0.38

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#672]
**Motivation**

See https://github.com/falcosecurity/falco/issues/3132

**Feature**

Add a new Grafana dashboard for Falco metrics.

**Additional context**

- TBD: We still have to think about the shape of the dashboard and how to present the metrics.

/assign
/assign @alacuku

**Comment by incertum** [comment]
Thanks @leogr for opening this dedicated issues.

Perhaps we need multiple dashboards. 
- One dashboard could be tailored to replace https://github.com/falcosecurity/falco-exporter
- Another one could be focused on performance overhead tracking, we could use it for https://github.com/falcosecurity/cncf-green-review-testing/issues/12
- ... more specialized dashboards given that we have a lot of metrics users can tap into

**Comment by incertum** [comment]
@leogr another question re the rules counters. We sanitize the rules name to conform with the Open Metric standard. should we maybe add the original rules name (all original characters) as label as well so it can be displayed more nicely in the dashboard?

**Comment by paltaa** [comment]
Hey, are there any available Grafana dashboards for the new exposed metrics? or any any PrometheusRule CRDs for Alerts on the new metrics?

**Comment by Issif** [comment]
@paltaa we're still working on the dashboard. The metrics feature is not stable yet, and the upcoming 0.39.0 will introduce breaking changes. 

Here's an overview of the WIP: https://issif.grafana.net/dashboard/snapshot/esulWY0cuRhb31SlqFDUHw3KJDHS4bq7?from=2024-09-13T19:53:02.224Z&to=2024-09-18T19:07:10.632Z&timezone=browser&var-datasource=grafanacloud-prom&var-source=k8s_audit&var-source=syscall&var-priority=$__all&var-rule=$__all&refresh=

**Comment by paltaa** [comment]
Hey @Issif, thanks for the quick response, could you share the JSON for that dashboard?

**Comment by Issif** [comment]
here: https://gist.github.com/Issif/608490eb42bdd321fd246060a6b7da42

**Comment by alacuku** [comment]
The dashboard has been integrated into the charts: https://github.com/falcosecurity/charts/pull/760
