### ISSUE TITLE
falcosidekick: WEBUI_URL - port incorrectly rendered as float64

### ISSUE THREAD

**Issue by tberreis** [falcosecurity/charts#686]
**Describe the bug**

With https://github.com/falcosecurity/charts/pull/685 the webui port was replaced by a variable which seems to be not rendered as expected. The WEBUI_URL is getting a wrong value and falco events are no longer visible within the UI at least for me.

**How to reproduce it**

Enable the webui, render the secrets.yaml and have a look at the base64 decoded value:
```
# helm template -s templates/secrets.yaml . | yq '.data.WEBUI_URL|@base64d'
http://release-name-falcosidekick-ui:%!s(float64=2802)
```

**Expected behaviour**

The port should be correctly set within the WEBUI_URL.
For the example above it would be `http://release-name-falcosidekick-ui:2802`.

**Screenshots**

**Environment**

- Falco version: 0.38.0
- Cloud provider or hardware configuration: AKS 1.29.4
- OS: Ubuntu 22.04.4 LTS

- Kernel: 5.15.0-1061-azure

- Installation method: Kubernetes

**Additional context**

**Comment by Issif** [comment]
cc @Sryther
