### ISSUE TITLE
Create PodMonitor or ServiceMonitor for Falco

### ISSUE THREAD

**Issue by ctdfo** [falcosecurity/charts#692]
**Motivation**
Falco exposes a `metrics` endpoint through its webserver, but there's no `PodMonitor` or `ServiceMonitor` configured for Prometheus to scrape the metrics from the endpoint. 

**Feature**
Add a `PodMonitor` and/or `ServiceMonitor` for Prometheus to scrape the metrics from the `metrics` endpoint. 

**Alternatives**
N/A

**Additional context**
The `prometheus_metrics_enabled` value in the Falco chart is a bit misleading since it only allows to expose the metrics but doesn't enable Prometheus to scrape those metrics. Also, there's a `ServiceMonitor` already configured in the charts for falcosidekick, falco-exporter and k8s-metacollector.
![image](https://github.com/falcosecurity/charts/assets/140103998/d60f58ee-0e08-41f2-bc90-96fc5f7f6e1e)

**Comment by alacuku** [comment]
Hi @ctdfo, we have a tracking issue for the grafana dashboard and metrics support in the charts: https://github.com/falcosecurity/falcoctl/issues/505

**Comment by jemag** [comment]
thanks for the info @alacuku . Hopefully we can still keep this one open, since it's easier to track/find for users of the helm chart.

**Comment by alacuku** [comment]
Hey @ctdfo, @jemag the support for Falco metrics has been merged: https://github.com/falcosecurity/charts/pull/700
