### ISSUE TITLE
event-generator launched through helm chart, can't run k8saudit tests

### ISSUE THREAD

**Issue by cam-at-tactiq** [falcosecurity/charts#723]
**Describe the bug**

event-generator launched through helm chart, can't run k8saudit tests

**How to reproduce it**

```
  helm install event-generator-k8saudits falcosecurity/event-generator \
    --namespace event-generator \
    --create-namespace \
    --set config.loop=false \
    --set config.actions="^k8saudit"
```

**Expected behaviour**

K8S rules should run, instead we get the error:
`Error: none of the selected actions is enabled
FATA error executing event-generator               error="none of the selected actions is enabled"`

**Environment**

- Falco version:

- System info: 4.7.2

- Cloud provider or hardware configuration:
- OS: GKE

- Kernel: 

- Installation method: Helm

**Additional context**

**Comment by cam-at-tactiq** [comment]
Please see the issue https://github.com/falcosecurity/event-generator/issues/212 originally raised by [alfredomagallon](https://github.com/alfredomagallon).

The fix for this is to add `--all` in the pod template here https://github.com/falcosecurity/charts/blob/ba95f4cbf29a66727535c9460aa8b4f6a778b1f1/charts/event-generator/templates/pod-template.tpl#L26

**Comment by cam-at-tactiq** [comment]
This is still an issue with an open PR at #725 to fix it, is anyone able to review that PR?

**Comment by Andreagit97** [comment]
Ei! Thank you for the proposed fix we will take a look ASAP! @alacuku

**Comment by leogr** [comment]
Hey
@cam-at-tactiq, this should be fixed now. May you confirm? Thanks

**Comment by cam-at-tactiq** [comment]
@leogr yes this is fixed now, thank you.
