### ISSUE TITLE
Use redis-cli ping command instead of tcp socket to attest readiness of the redis-stack:7.2.0-v11

### ISSUE THREAD

**Issue by damienvergnaud** [falcosecurity/charts#732]
Concerned lines :
https://github.com/falcosecurity/charts/blob/46516b090cc91d4c89630b91c393cf15e37ddac5/charts/falcosidekick/templates/deployment-ui.yaml#L211C1-L218C32

Based on : 
https://stackoverflow.com/questions/64068179/readiness-probe-for-redis-with-large-dataset

Because if i observe logs of one starting pod : 

```
│ 9:C 28 Aug 2024 13:58:53.127 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo                                                                                                                                    │
... REMOVED LINES ...   
│ 9:M 28 Aug 2024 13:59:56.320 * Ready to accept connections tcp                                                                                                                                                  │

```

In some cases, the others falco pods may think the service is ready to receive calls, which is not the case.

Correction that supposedly work (I verified the presence of redis-cli ping command inside the container).
It only respond "PONG" when redis is really READY to receive calls.

```
 readinessProbe:
  exec:
    command:
    - redis-cli
    - ping
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 3
```

Hope it helps ;)

**Comment by Issif** [comment]
This is a good proposal, I'll test that solution

**Comment by Issif** [comment]
Done with #740
