### ISSUE TITLE
Feature request: Pass values to k8s-meta-collector

### ISSUE THREAD

**Issue by mvtab** [falcosecurity/charts#734]
A best practice in Helm Charts is to pass all values from a chart to the used subcharts.

## Problems

1. The subchart k8s-meta-collector is called "kubernetes" in the falco Chart. This is misleading, hiding the fact that we are talking about the k8s-meta-collector subchart.
2. Any values given to the "kubernetes" key are not propagated to the subchart. This makes it impossible, for example, to set resource limits to the k8s-meta-collector.

**Comment by alacuku** [comment]
Hey @mvtab,

>     1. The subchart k8s-meta-collector is called "kubernetes" in the falco Chart. This is misleading, hiding the fact that we are talking about the k8s-meta-collector subchart.

The subcharts is called `k8s-metacollector` that's defined here: https://github.com/falcosecurity/charts/blob/4d2da46d13bf580026fcb9286cb017d6c6f749fe/charts/falco/Chart.yaml#L25-L28

>     2. Any values given to the "kubernetes" key are not propagated to the subchart. This makes it impossible, for example, to set resource limits to the k8s-meta-collector.

So if you need to set values for the subchart you need to use the `k8s-metacollector` key such as:
```bash
helm install falco falcosecurity/falco \
    --namespace falco \
    --create-namespace \
    --set tty=true \
    --set driver.kind=ebpf \
    --set collectors.kubernetes.enabled=true \
    --set k8s-metacollector.serviceMonitor.create=true \
    --set k8s-metacollector.serviceMonitor.labels.release="kube-prometheus-stack" \
    --set k8s-metacollector.grafana.dashboards.enabled=true
```

**Comment by mvtab** [comment]
This works, thank you.

**Comment by mvtab** [comment]
One quick question still, if you are mentioning the dashboards. They look like this at me:
![image](https://github.com/user-attachments/assets/76a80f68-9efe-4cc6-8840-50ae219dc476)

Am I missing some scrappers? I also tried some other falcosec dashboards, all return same results.
