### ISSUE TITLE
Add the CHANGELOG.md to falcosidekick

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#79]
**What to document**

Currently, the `falcosidekick` chart has no changelog. It would great if we introduced it.

**Comment by Issif** [comment]
Ok, the changelog is only for what concern the helm chart?

**Comment by leogr** [comment]
> Ok, the changelog is only for what concern the helm chart?

Yes, exactly.

BTW: Unfortunately, it's a manual process - I know. Anyway, it's not needed to be too precise, but at least it will help folks to understand what has changed. Also, I'd like to automatize that in the future, any idea about that is welcome!

**Comment by Issif** [comment]
Ok, will try to do so asap
