### ISSUE TITLE
dnsPolicy should be set to ClusterFirstWithHostNet in pod template with gVisor driver

### ISSUE THREAD

**Issue by NoOverflow** [falcosecurity/charts#793]
Hi,

**Describe the bug**

The dnsPolicy attribute is currently only set to ClusterFirstWithHostNet when the driver kind is `ebpf` and hostNetwork is enabled. https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/pod-template.tpl#L36-L38

This is due to how dnsPolicy behaves when hostNetwork is true (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy)

> "ClusterFirstWithHostNet": For Pods running with hostNetwork, you should explicitly set its DNS policy to "ClusterFirstWithHostNet". Otherwise, Pods running with hostNetwork and "ClusterFirst" will fallback to the behavior of the "Default" policy."

The "Default" policy uses the DNS resolve configuration from the node, this effectively isolate the pod from resolving the IP of other pods/services on the cluster. 

Since the dnsPolicy attribute is not set when the driver is gVisor, but the hostNetwork attribute is. This causes dnsPolicy to fallback to this Default mode. 

https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/pod-template.tpl#L60-L63

This is an issue especially when you enable the http output to falcosidekick, because the URL is automatically set to `falco-falcosidekick:2801` and fails to lookup, causing an issue similar to https://github.com/falcosecurity/falco/issues/3142.

**How to reproduce it**

Deploy falco with the gVisor driver, and the falcosidekick pod enabled.

Example values file:
```YAML
falcosidekick:
  enabled: true
driver:
  enabled: true
  kind: gvisor
  gvisor:
    enabled: true
````

**Expected behaviour**

`dnsPolicy` should be set to `ClusterFirstWithHostNet` when `driver.kind: gvisor`

**Comment by NoOverflow** [comment]
Fix commit on my fork, https://github.com/NoOverflow/falco-charts/commit/c35f23515ee848516ac34505f18f76bed90b5316. Let me know if you want me to open a PR :)

**Comment by Issif** [comment]
The setting https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/values.yaml#L469 set to `true` allows to use the fqdn and avoid the issue, right?

**Comment by NoOverflow** [comment]
> The setting
> 
> https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/values.yaml#L469
> 
> set to `true` allows to use the fqdn and avoid the issue, right?

This flag seems to only set the sidekick url in the configuration to the full URL, but it would still need to be able to resolve it using the Kubernetes internal DNS, so no I'm pretty sure it wouldn't avoid it

https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/_helpers.tpl#L140-L144

(http://falco-falcosidekick:2801 > http://falco-falcosidekick.falco.svc.cluster.local:2801 when it's enabled)

**Comment by Issif** [comment]
I see, feel free to propose a PR to add the setting when gvisor is enabled. Thanks
