### ISSUE TITLE
[Falco 0.23.0] Falco pod is failing in kubernetes cluster due to dkms build failed

### ISSUE THREAD

**Issue by SamarSidharth** [falcosecurity/charts#80]
**Describe the bug**
I am trying to install falco on my RHEL 7.7 k8s cluster but the falco pod goes into error state due to dkms build failed

Falco prebuilt module not getting downloaded is expected as there is no internet connectivity in the env, but in case of RHEL it is looking for the module with rhel as a prefix whereas the module exists with centos prefix in the repository

**How to reproduce it**
Running helm chart with default value from following link https://github.com/falcosecurity/charts/tree/master/falco

**Expected behaviour**
The falco kernel module should be built by the falco pod and it should be in a running state with falco working

**Screenshots**

 kubectl logs -f falco-hgv5b -n security
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/96bd9bc560f67742738eb7255aeb4d03046b8045/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 3.10.0-1062.12.1.el7.x86_64, if present
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_rhel_3.10.0-1062.12.1.el7.x86_64_1.ko
curl: (7) Failed to connect to dl.bintray.com port 443: Connection timed out
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Wed Aug 26 08:31:58 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Aug 26 08:31:58 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Aug 26 08:31:59 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed Aug 26 08:31:59 2020: Unable to load the driver. Exiting.
Wed Aug 26 08:31:59 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.

**Environment**

- Falco version: 0.23.0

- System info: 
falco --support | jq .system_info
Wed Aug 26 11:44:01 2020: Falco version 0.25.0 (driver version ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7)
Wed Aug 26 11:44:01 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Aug 26 11:44:01 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Aug 26 11:44:02 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
{
  "machine": "x86_64",
  "nodename": "falco-mwgmw",
  "release": "3.10.0-1062.12.1.el7.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Thu Dec 12 06:44:49 EST 2019"
}

- Cloud provider or hardware configuration:
- OS:
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)

- Kernel:
uname -a
Linux m1-kms0001.mgmt.oiaas 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

- Installation method:
Kubernetes

**Additional context**

**Comment by leogr** [comment]
Hi @SamarSidharth 

thanks for reporting this here!

Anyway, what's the version are you using? 0.23.0 or 0.25.0?
Also, what's the helm chart version?

Please, also - in case you didn't do that yet -  try with the latest Falco chart (v1.3.0) that comes with Falco 0.25.0

**Comment by SamarSidharth** [comment]
Hi @leogr 

I am using falco 0.23.0 with helm chart version: 1.1.9.
I will try it with the new version of falco and helm chart and will let you know the results.

Regards,
Samar Sidharth

**Comment by SamarSidharth** [comment]
Hi @leogr 

I have tried it with the latest version(falco: 0.25.0 and helm chart: 1.3.0) but result is still the same.



falco                                           1               Wed Aug 26 13:47:53 2020        DEPLOYED        falco-1.3.0                         0.25.0          default


kubectl logs -f falco-49mg9
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 3.10.0-1062.12.1.el7.x86_64, if present
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/falco_rhel_3.10.0-1062.12.1.el7.x86_64_1.ko

**Comment by SamarSidharth** [comment]
Hi @leogr 

Thanks a lot for your valuable suggestion the issue got fixed after installing kernel header on my host machine.

Regards,
Samar Sidharth

**Comment by leogr** [comment]
Hi @SamarSidharth 

you are welcome!

Since this has been solved, but we still have a documentation problem, I have opened an issue here :point_right: https://github.com/falcosecurity/falco-website/issues/240 and closing this.

Thank you, again, for reporting this!
