### ISSUE TITLE
Error loading rules: Unknown event/syscall "renameat2"

### ISSUE THREAD

**Issue by irivera007** [falcosecurity/charts#91]
Following the same comment here: https://github.com/falcosecurity/falco/issues/1380
Im seeing the same issue using charts.
Im wondering when this change https://github.com/falcosecurity/falco/pull/1381
is gonna get ported here.

Thank you

**Comment by leogr** [comment]
If you see that issue, I guess you're using Falco 0.24.0 with newer rules. Please make sure you have the latest chart version (that includes the ruleset for Falco 0.25.0) and using Falco 0.25.0.

https://github.com/falcosecurity/falco/pull/1381 has been just merged into the master branch but it's not yet released neither on Falco nor here.
Usually, when the new Falco release is available we also update here shortly after (releasing a new chart version).

**Comment by irivera007** [comment]
Hi @leogr Thank you for the insight

That did the trick, thank you, there was an extra values.yaml that was overriding the the falco version,
Again thank you so much!

**Comment by leogr** [comment]
You are welcome!

I'm closing this since the expected behavior is that "the lastest chart version is just intended to work with the last Falco version".

/close
