### ISSUE TITLE
Add an example of how to use `extraInitContainers` configuration.

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#92]
**Motivation**

See #36 and https://github.com/falcosecurity/charts/pull/89#pullrequestreview-488882738

**Feature**

Add an example of how to use `extraInitContainers` configuration.

**Alternatives**

**Additional context**

We may need an extra mount to pass the driver from the init container to the Falco container.
Thanks to @Fsero for his PR #89 and the [initial example](https://github.com/falcosecurity/charts/pull/89/files/6ecaec0918dc6dea00753fd0e9be432f6881a360#diff-c075bcc0c10d27070497f11bed4f0cccR347) (that has been removed in favor of this issue).

**Comment by perezjasonr** [comment]
second this motion, I immediately wanted to try the driver as an initContainer but realized I couldn't add a volume for .falco path

**Comment by leogr** [comment]
I believe we need something like `extraInitVolume`. It would great if someone could help with that. 
@perezjasonr btw, feel free to make a PR!

**Comment by perezjasonr** [comment]
> I believe we need something like `extraInitVolume`. It would great if someone could help with that.
> @perezjasonr btw, feel free to make a PR!

I believe we do too.
Sure I can maybe look into trying to contribute, although I'd be starting from scratch I haven't looked at the inner workings/code. Whats the best way to get started?

**Comment by leogr** [comment]
Take a look at #36. Also, the Grafana Helm chart did about the same thing, that could be inspirational :point_right: https://github.com/helm/charts/pull/12343/files 

Moreover, note that an extra dir mount can be handy for the eBPF probe use case. Unlike the kernel module, the probe needs to be passed (as a `.o` file) to the Falco process that will load it at runtime. The default path where Falco looks for a probe is `/root/.falco/`.

**Comment by perezjasonr** [comment]
@leogr 
im actually still considering contributing and trying to implement this, but from what im seeing a lot of this is in C++?
should I only pursue being a contributor if I'm confident in C++ because I certainly am not.

**Comment by leogr** [comment]
> @leogr
> im actually still considering contributing and trying to implement this, but from what im seeing a lot of this is in C++?
> should I only pursue being a contributor if I'm confident in C++ because I certainly am not.

Hey @perezjasonr 

it would be great if you contributed, and there are a lot of things that do not require C++  knowledge. There's no need for C++ to solve this specific issue, for example. :smiley: 

If you are interested or just want to chat about this, you can find me and the rest of the community in the #falco slack channel on the Kubernetes slack. I will be happy to help :)

**Comment by perezjasonr** [comment]
I think I'm gonna take you up on that offer. if you could get me up on my feet I see no reason I can't pull this off. While I'm not confident in C++ im very confident in helm and k8s.
