### ISSUE TITLE
Integrate Falco exporter into Falco pod

### ISSUE THREAD

**Issue by dza89** [falcosecurity/charts#97]
**Motivation**
So right now Falco and Falco-exporter are two different helm charts resulting in two different pods, which are pretty much dependent on each other. I have two issues with that:

1. The easiest way to setup is using the gRPC socket. Which means both pods need a extra host mount to set up communication. This is not a best practice. It would be better to setup communication through networking. If choosing for that, it makes way more sense from multiple perspectives to have Falco and the exporter in the same networking space. (both containers in the same pod) 

2. We are running AKS and EKS, with the native cni. Which means that each node has a maximum amount of ips to distribute to the pods. When I have to spin up an extra daemonset it costs our developers 1 * #nodes pods to spin up. 
-->

**Feature**
I'm willing to make a pr to integrate Falco exporter into the Falco helm chart. But I get that feeling that you guys want to keep the helm chart as slim as possible, which also makes sense. (I opened a pr for falco-ekscloudwatch before) Hence opening this ticket. 

**Alternatives**

Another idea would perhaps to create two Falco charts:

Falco-slim: the bare minimum included to deploy Falco. 
Falco-full: all extensions included 

**Additional context**

Na

**Comment by leogr** [comment]
Hi @dza89 

Thanks for bumping this topic up.

TBH, I would not like a big full-featured chart, for several reasons:
- the chart would be more complex to test and maintain 
- there's a legit use case where Falco is directly installed on the host (so no pod or container); in that case, a separate falco-exporter chart will be still needed
- other tools using the gRPC API may be added in the future; thus, we will even need to an extra host mount to set up communication

However, I perfectly understand your points, and I agree we should try to find a way that solves those issues. 

Thus, IMHO it worths investigating any valid alternative to the current design (eg. [subcharts](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/) might help?) and discussing that with the community.
Feel free to propose this discussion in the weekly [Falco community call](https://github.com/falcosecurity/community#falco-community-calls) too.

**Comment by dza89** [comment]
Subcharts won't help as I want to place falco-exporter in the same deployment as Falco.
That's why I also suggested to split it into two charts: falco-full and falco-slim.
But maybe I should just fork it. Close for now.
